### ISSUE TITLE
Assuming DNS packet contains NULL delimiter, possible segfault?

### ISSUE THREAD

**Issue by lambdaupb** [objective-see/LuLu#103]
https://github.com/objective-see/LuLu/blob/38bd210c976579ce899c108cdc06b6e46681d25d/launchDaemon/launchDaemon/KextListener.m#L699

If I read this correctly, this code assumes that the DNS packet is well formed.
An adversary could send a packet with length greater 512 byte length that does not contain any 0 bytes and crash the userspace process.

I did not test this though.

**Comment by objective-see** [comment]
Fix pushed/merged into [version 1.2.0](https://github.com/objective-see/LuLu/releases/tag/v1.2.0)
