### ISSUE TITLE
dnsCache is never cleared, causing possible memory exhaustion attack

### ISSUE THREAD

**Issue by lambdaupb** [objective-see/LuLu#104]
https://github.com/objective-see/LuLu/blob/38bd210c976579ce899c108cdc06b6e46681d25d/launchDaemon/launchDaemon/KextListener.m#L66

I can't find a place where entries are evicted from the dnsCache, making it possible for a remote attacker to cause a memory exhaustion by sending gigabytes of unsolicited random DNS responses to port 53.

Did not try this though.

**Comment by lambdaupb** [comment]
Thanks for looking into it.
This does not seem to limit the total size of the lookup table, especially if it is maliciously inflated by unrequested DNS answer packets in a span of <24h.

**Comment by objective-see** [comment]
good point 😅

thoughts on "take two": https://github.com/objective-see/LuLu/blob/5b08370e98281fb4f0c61fafd19b63ca776d6dbc/launchDaemon/launchDaemon/KextListener.m#L925

**Comment by objective-see** [comment]
Changes pushed/merged into [version 1.2.0](https://github.com/objective-see/LuLu/releases/tag/v1.2.0)
