### ISSUE TITLE
Display alert window on all spaces

### ISSUE THREAD

**Issue by KizzyCode** [objective-see/LuLu#108]
I'm working with multiple spaces and sometimes it happens that the alert window does not appear on my current space (probably due to fast switching at the wrong time).

IMHO it would be a good idea to display the alert window on all spaces using `self.window.collectionBehavior = .canJoinAllSpaces` in `AppDelegate` (as ObjC code of course).

**Comment by objective-see** [comment]
Great suggestion! 
Per your suggestion, added `NSWindowCollectionBehaviorCanJoinAllSpaces`: https://github.com/objective-see/LuLu/blob/a6b38bb8b72f15013a506d4da7290dfc99a3461d/shared/XPCUser.m#L44
