### ISSUE TITLE
Uninstallation always removes settings

### ISSUE THREAD

**Issue by KizzyCode** [objective-see/LuLu#114]
The current uninstallation always removes the settings which breaks the "uninstall old version/reinstall new version" workflow performed by Homebrew's Cask (see [here](https://github.com/Homebrew/homebrew-cask/issues/53078) or [here](https://github.com/Homebrew/homebrew-cask/pull/56218)).

Is it possible to implement a switch like `-uninstall_keep_prefs` to allow an uninstallation without purging the settings (like `apt-get purge` vs. `apt-get remove`)?

**Comment by objective-see** [comment]
The installer, will perform a 'partial' uninstall if it detects that LuLu is already installed - leaving the settings intact. (i.e. its an upgrade).

But yah, invoking uninstall, will, well uninstall everything! 

Ideally the homebrew cask could be updated to just call install :)

**Comment by KizzyCode** [comment]
Yeah, we discussed this and I don’t see it coming that this will change... in my opinion you’re right because an uninstall-install-step is a reinstallation which is sth. different than an upgrade. However if the auto-updates are fixed (#91), the formula could be marked as auto-updating which would circumvent this problem.
