### ISSUE TITLE
LuLu 1.1.2 installer stuck while enumerating apps

### ISSUE THREAD

**Issue by lehrig** [objective-see/LuLu#117]
On my Mac/Mojave, the LuLu 1.1.2 installation is stuck while "Enum'ing installed apps ...please wait!". I have waited for approximately 5 hours without any progress.

**Comment by objective-see** [comment]
Hrmm, to enumerate apps, it simply invokes macOS's `system_profiler` utility and waits till that exits.

Can you replicate this? And if so, can you confirm that `system_profiler` is still running (after x hours). 
If  installer gets stuck **and**`system_profiler` has exited, this would seem to indicate another bug/issue that I'll try track down!

**Comment by andrey-snowflake** [comment]
Ran into similar issue. Finished after being a little more patient. Also helped to 

    sudo ps -A | grep system_profiler

and stare at it a little bit.

**Comment by lehrig** [comment]
- after a restart, LuLu seemed to work normal; even though I aborted the installer
- I reinstalling with LuLu 1.2.0 & the issue did not occur anymore - so it seems to be resolved

Thanks!
