### ISSUE TITLE
Huge CPU load

### ISSUE THREAD

**Issue by AykutCevik** [objective-see/LuLu#12]
I experienced a huge CPU load after restarting the system and starting several apps.
![CPU](https://user-images.githubusercontent.com/1965251/30798579-733e4314-a1da-11e7-89ef-5538857f0bf0.png)
The load got normal after few minutes. Since this is an alpha version it may be helpful for you. Otherwise just close it :)

Thank you for this great app!

**Comment by evil5hadow** [comment]
First of  all, thank you for this great **open source** app!

Same issue here: LuLu v.0.9.4 is constantly eating around 50%-60% which is a lot for a single app.
Let me know if you need extra info (logs) on this matter.

Keep up the good work!

**Comment by objective-see** [comment]
Ah sorry about this! if you could send me a sample (which shows where the various threads are hanging out) that'd be super helpful! email: bugs@objective-see.com 

Via Activity Monitor: click on process, click the 'i' icon (top left), in the new window, click 'Sample' (bottom left).

Via Terminal: sudo sample pidOfLuLu

...also maybe some output from the log file? 
Via Terminal: log show | grep -i lulu 

Mahalo!

**Comment by evil5hadow** [comment]
I've noticed that LuLu is CPU hungry while using [Ubersicht](http://tracesof.net/uebersicht). 
Logs sent over email.

Thanks!

**Comment by objective-see** [comment]
Thanks for the feedback and logs! Looks like the CPU issue was related to computing code-signing information for new processes in an inefficient manner. 

The [latest version, 0.9.7](https://github.com/objective-see/LuLu/releases/tag/0.9.7) uses a more efficient API / flags/ algorithm to compute the code-signing information for new processes 

Please give it a whirl and let me know if the issue still present :)

**Comment by evil5hadow** [comment]
The latest version (0.9.7) works great! CPU usage dropped **a lot** (2%-7% tops).
Thank you for all your hard work you put on this project!

Keep up the good work!

**Comment by objective-see** [comment]
mahalo for the kind words!!
 -and happy this fixed your issue 👍
