### ISSUE TITLE
Unsigned `__MACOSX/._LuLu Installer.app` in LuLu_1.2.0.zip

### ISSUE THREAD

**Issue by githubnww** [objective-see/LuLu#124]
On Sierra, unzip LuLu_1.2.0.zip extracts unsigned `__MACOSX/._LuLu Installer.app` (double underscore) into the current directory, outside `LuLu Installer.app`
```
$ ls -lA __MACOSX
total 8
-rw-r--r--@ 1 xxxxxx  staff  210 Feb 16 14:39 ._LuLu Installer.app

$ codesign -dv --verbose=4 '__MACOSX/._LuLu` Installer.app'
__MACOSX/._LuLu Installer.app: code object is not signed at all
```
Lulu 1.2.0 installs without issue after `rm -rf __MACOSX`

**Comment by objective-see** [comment]
Thanks for the bug report.
...switched to a .dmg for distribution so this issue should now be fixed!
