### ISSUE TITLE
Xcode Simulator 

### ISSUE THREAD

**Issue by mickspecial** [objective-see/LuLu#144]
How to prevent showing connection alert every time my simulator starts ?

**Comment by rbruels** [comment]
You can work around this by specifying "Apply Rules Globally". 

<img width="537" alt="Screen Shot 2020-04-12 at 10 27 50 PM" src="https://user-images.githubusercontent.com/338962/79094625-ffa05a80-7d0c-11ea-87c0-b333c46a1741.png">

**Comment by skywinder** [comment]
@rbruels where is this checkbox? can't find in int the settings

**Comment by oxmix** [comment]
@skywinder 
<img width="598" alt="Screenshot 2020-11-20 at 10 42 49" src="https://user-images.githubusercontent.com/1283362/99773632-cab77a00-2b1d-11eb-9b11-4b96e0601e7c.png">

**Comment by aheze** [comment]
@oxmix is it still here in LuLu 2.0.0? This is what I see:

![Screen Shot 2020-12-28 at 7 29 09 PM](https://user-images.githubusercontent.com/49819455/103256695-06c2d380-4943-11eb-96c4-9ad8fd1a3775.png)

**Comment by oxmix** [comment]
@aheze I don't know where is this setting now :)

**Comment by aheze** [comment]
@oxmix no problem, I will let you know if I find it.

**Comment by oxmix** [comment]
@aheze ok, thx)
