### ISSUE TITLE
macOS Catalina issues

### ISSUE THREAD

**Issue by hashimda** [objective-see/LuLu#149]
### Certain aspects of this application seem to not work on macOS Catalina, such as:
- The application having broken graphics and icons when it comes to most programs.
- Blocking applications seems to not be working correctly. (As in it appears that blocking isn't actually working)
- Issues with setting rules (the rules list glitching out and not working correctly).

Does anyone else seem to have issues with this app on the latest version of macOS (Catalina 10.15), or am I doing something wrong (such as app permissions etc)? Does this application support macOS Catalina at the moment?. Thanks in advance.

**Comment by Brido-99** [comment]
Same here, can't load rules. Doesn't appear to be blocking.

**Comment by qtumev** [comment]
+1. This is the most important App for me, so much that I have reverted back to Mojave!
Please, if you have the time, update the app.
Thank you again for your time and effort!

**Comment by alvarnell** [comment]
> +1. This is the most important App for me, so much that I have reverted back to Mojave!
Note that there hasn't been any work performed on this software for eight months now and there are currently 72 open issues. I know the developer is extremely busy with his day job and several other side issues, so it may well be time to look for an alternate solution.

**Comment by stepini** [comment]
If I know there are no free solution :(:(
Little snitch but not free... any ideas?
Stefano

---
Stefano Pini
stepini@gmail.com

**Comment by Skalda555** [comment]
My Catalina work fine!

**Comment by hashimda** [comment]
Update: 
LuLu 1.2.1 works perfectly on macOS Catalina, this issue can be closed.
Take note that LuLu on GIthub is not updated, in this link:
https://github.com/objective-see/LuLu/releases

However, LuLu from Objective See's website https://objective-see.com/products/lulu.html,
works perfectly on macOS Catalina, since it is at version 1.2.1.
