### ISSUE TITLE
Few allow/deny windows at onetime

### ISSUE THREAD

**Issue by n0taz** [objective-see/LuLu#15]
I think good idea if that will have possibility to show few allow/block requests at one time (now only 1 from queue), cause:

1) installed LuLu
2) saw unknown process and unknown ip address
3) trying whois, but no way, cause i can't allow whois traffic until close previous window

**Comment by objective-see** [comment]
Yes agreed!
Good news, recent versions of LuLu now display multiple alerts at one time :)
