### ISSUE TITLE
Import LuLu rules not working in MacOS Catalina

### ISSUE THREAD

**Issue by vishdaily** [objective-see/LuLu#155]
Hello,

I upgraded to MacOS Catalina couple of days back. Since then, import rules to Lulu doesn't work any more. import rules result always emptying out all the rules. Could any one suggest a work around till there is a LuLu fix for this ?

**Comment by niclasgelin** [comment]
To circumvent to problem, disable LuLu before manually importing your rules.

And this method also seem to work as expected:

```
sudo cp /Library/Objective-See/LuLu/rules.plist /Library/Objective-See/LuLu/rules.plist.bak
sudo cp /path/to/exported/rules.plist /Library/Objective-See/LuLu/rules.plist
sudo chown root:wheel /Library/Objective-See/LuLu/rules.plist
sudo chmod 644 /Library/Objective-See/LuLu/rules.plist
sudo killall -HUP LuLu
```

**Comment by niclasgelin** [comment]
To work around the problem, disable LuLu before manually importing your rules.

This method also seem to work:

```
sudo mv /Library/Objective-See/LuLu/rules.plist /Library/Objective-See/LuLu/rules.plist.bak
sudo cp /path/to/exported/rules.plist /Library/Objective-See/LuLu/rules.plist
sudo chown root:wheel /Library/Objective-See/LuLu/rules.plist
sudo chmod 644 /Library/Objective-See/LuLu/rules.plist
sudo killall -HUP LuLu
```

**Comment by vishdaily** [comment]
Hello @niclasgelin, 

Thank you very much for instructions. Working like a charm. 👍 
I can perfectly live with this work around till the fix :)
