### ISSUE TITLE
Update popup doesn't name the app

### ISSUE THREAD

**Issue by Siguza** [objective-see/LuLu#158]
I just booted my Mac and was presented with this popup:

![Screenshot 2019-12-07 at 18 37 41](https://user-images.githubusercontent.com/1659374/70378529-9ef9af00-1921-11ea-8c27-874c7c324a77.png)

It wasn't hard to figure out that this this came from LuLu Helper, but my initial reaction was "a new version of... _what_?". Please consider adding a name to that popup? :)

**Comment by objective-see** [comment]
Opps, the build didn't pull in the icon image / text

Just fixed: https://github.com/objective-see/LuLu/commit/78ed18076c9844f5514267573ad00fc6d2caa6d9


![Screen Shot 2019-12-07 at 11 09 34 AM](https://user-images.githubusercontent.com/11327812/70380609-14458f80-18e2-11ea-9757-85a39d9773fd.png)
