### ISSUE TITLE
A new version is available

### ISSUE THREAD

**Issue by thisconnect** [objective-see/LuLu#159]
macOS 10.15.1 

A promt just appeared without any context. Please add that this is about Lulu app.

see screenshot:

![Screen Shot 2019-12-09 at 1 24 38 PM](https://user-images.githubusercontent.com/546900/70435713-cff3f400-1a87-11ea-84cb-e3e7c6ff0916.png)

**Comment by ctf0** [comment]
i've been getting this for about a week now 😕

**Comment by sogen** [comment]
yes, you should update

**Comment by objective-see** [comment]
Sorry,  the previous builds didn't pull in the icon image / text
Just fixed: 78ed180 (and #158)

https://user-images.githubusercontent.com/11327812/70380609-14458f80-18e2-11ea-9757-85a39d9773fd.png

**Comment by ctf0** [comment]
`1.2.2` is not avail https://github.com/objective-see/LuLu/releases
