### ISSUE TITLE
Re-importing an exported rules.plist does not work

### ISSUE THREAD

**Issue by KizzyCode** [objective-see/LuLu#160]
I've exported the rules plist before I updated LuLu using `brew cask`, however importing does not work. When I import my rules.plist (see attachment), it only deletes all existing rules without importing the ones from the plist.

OS: Catalina 10.15.1 (19B88)
LuLu: 1.2.2

[rules.plist.txt](https://github.com/objective-see/LuLu/files/3939672/rules.plist.txt)

**Comment by elbotho** [comment]
Sound like #155
There are some 2 workarounds there.
One of the issues should stay open!
