### ISSUE TITLE
Add keyboard shortcuts (i.e. cmd + h (hide) / m (minimise) / w (close)) #Enhancement #Suggestion

### ISSUE THREAD

**Issue by ldexterldesign** [objective-see/LuLu#192]
Hi!

Hope you're well

Thanks for splendid FOSS software

As title

Also, please correct me if I'm wrong but `cmd + q` should quit the application not close the window and leave something in the toolbar - that's what `cmd + w` (close) is for

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Hope this helps and to hear back

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.3 (19D76)
software - application: LuLu, 1.2.3

**Comment by bmironer** [comment]
+1 for command-w in all windows

**Comment by pwardle** [comment]
Thanks for the patience! 

Latest version of the 2.0.0 beta supports such keyboard shortcuts/hot-keys.

If you want to test it out and provide any feedback, I'd be super appreciate:
https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip

**Comment by nhojb** [comment]
Update: just installed the latest build.

There are still issues with keyboard shortcuts in windows:

Rules: Cmd+W works
Preferences: Cmd+W works, Cmd+M does not.
Network Monitor: Neither Cmd+W or Cmd+M work.

**Comment by ldexterldesign** [comment]
Hi @pwardle,

Thanks for reply, and - unless I missed it in previous versions - thanks for adding a network monitor!:

<img width="1904" alt="Screenshot 2020-10-02 at 01 29 55" src="https://user-images.githubusercontent.com/1715809/94876175-cbe9f600-044e-11eb-83ec-7727185d9e60.png">

I installed your beta but, disappointingly, there's no shortcut change(s) for me in latest macOS - have you tested in macOS?

Hope to hear back

Sincerely

**Comment by ldexterldesign** [comment]
I take it back `cmd + h (hide)` and `cmd + w (close)` function now, which is great, but can we get `cmd + m (minimise)` too?

Hope to hear back

Apologies

**Comment by objective-see** [comment]
Thanks for the feedback
-added support for +m (minimize)
-added support for +f (find, for the rules window)

The network monitor, is actually a separate application (Netiquette) - so will be updated later!

**Comment by ldexterldesign** [comment]
Lastly, please add `cmd + ,` (i.e. preferences)

How can I test these in the beta?

Sincerely

**Comment by objective-see** [comment]
@ldexterldesign 
just uploaded new beta: https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip

Also rebuilt the network monitor app to support hotkeys ....but again, note it is a separate app (packaged/launched by LuLu), so a cmd+q for example, in the network monitor will quit it - but won't quit LuLu.app
