### ISSUE TITLE
Add import/export of rules

### ISSUE THREAD

**Issue by vitorgalvao** [objective-see/LuLu#2]
Feature request: way to export and import rules. It’ll be particularly useful for fresh installs.

---

You likely already thought about this, but opening an issue nonetheless to keep track.

Thank you for all your great tools, and for adding CLI installs and uninstalls to all of them!

**Comment by objective-see** [comment]
https://github.com/objective-see/LuLu/commit/e0d140f830c071fbef422d60fe5d70906c0fed1d adds support for this feature.  ![screen shot 2017-09-17 at 11 24 53](https://user-images.githubusercontent.com/11327812/30525057-da08db4a-9b9a-11e7-9357-a6d3ac3cbc9f.png)
