### ISSUE TITLE
Quaisi-infinite "com.apple.geod" warning loop

### ISSUE THREAD

**Issue by nitriques** [objective-see/LuLu#20]
I've installed LuLu and worked on the computer for about an hour with it working, everything was just great. A couple of deamon ask for permissions, which I guess is normal with a new install.

But, when my work was done I just close the lid of my macbook and went to sleep. 36 hours later, after opening the mac I get many many many of the same warning, about Apple's geod deamon.

I know LuLu is still beta: this is not a complaint, rather just a bug report to help out.

Thanks for all of your amazing software/blog posts/talks/...

**Comment by alvarnell** [comment]
Same thing happened to me. Had to reboot to get rid of the notifications. Seems like they should time out rather than continue to multiply.

**Comment by cromulus** [comment]
Or perhaps collect multiple outbound requests from the same process into a single alert? Or perhaps re-process subsequent alerts through the ruleset so that once you hit allow or block all subsequent alerts are resolved/silenced?

**Comment by michaelhaessig** [comment]
Same thing happening to me.
The notification should be resolved for all pending connections at once.

**Comment by StefanDesu** [comment]
I agree. I always have to quit the helper process whenever I left the computer for a while and a seemingly infinite amount of the same alert for the same process have piled up.

**Comment by objective-see** [comment]
Sorry about this bug! Was recently fixed.
LuLu now contains logic to only show one alert per process -even if the computer is asleep.

**Comment by nitriques** [comment]
@objective-see Thanks patrick !
