### ISSUE TITLE
Causes the Mac to restart when it wakes from sleep

### ISSUE THREAD

**Issue by tactan** [objective-see/LuLu#201]
macOS 10.5.15
I had the same problem with Handsoff! before, and then changed to LuLu, the problem is still.

> panic(cpu 2 caller 0xffffff801b015f27): "AppleGFXHDADriver::setPowerState(0xffffff8052d55200 : 0xffffff7f9e8ca732, 0 -> 1) timed out after 10138 ms"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.121.2/iokit/Kernel/IOServicePM.cpp:5296
Backtrace (CPU 2), Frame : Return Address
0xffffff922d023b40 : 0xffffff801a91f5cd 
0xffffff922d023b90 : 0xffffff801aa58b05 
0xffffff922d023bd0 : 0xffffff801aa4a68e 
0xffffff922d023c20 : 0xffffff801a8c5a40 
0xffffff922d023c40 : 0xffffff801a91ec97 
0xffffff922d023d40 : 0xffffff801a91f087 
0xffffff922d023d90 : 0xffffff801b0c27cc 
0xffffff922d023e00 : 0xffffff801b015f27 
0xffffff922d023e50 : 0xffffff801b015809 
0xffffff922d023e60 : 0xffffff801b02cd9e 
0xffffff922d023ea0 : 0xffffff801b0145b8 
0xffffff922d023ec0 : 0xffffff801a961565 
0xffffff922d023f40 : 0xffffff801a961091 
0xffffff922d023fa0 : 0xffffff801a8c513e 

BSD process name corresponding to current thread: kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x000000001a600000
Kernel text base: 0xffffff801a800000
__HIB  text base: 0xffffff801a700000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO

System uptime in nanoseconds: 195029604119741
last loaded kext at 97317510268010: @filesystems.msdosfs	1.10 (addr 0xffffff7f9eccb000, size 69632)
last unloaded kext at 93915134743598: com.parallels.kext.hypervisor	14.1.3 45485 (addr 0xffffff7f9eccf000, size 204800)
loaded kexts:
com.objective-see.lulu	1.2.3
@filesystems.msdosfs	1.10
@filesystems.cd9660	1.4.4
|SCSITaskUserClient	422.120.3
>!UODD	489.120.1
@filesystems.smbfs	3.4.3
>AudioAUUC	1.70
>!AGraphicsDevicePolicy	5.2.4
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	5.2.4
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.5f6
>!AUpstreamUserClient	3.6.8
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
>X86PlatformShim	1.0.0
>pmtelemetry	1
>!A!IKBLGraphics	14.0.6
@Dont_Steal_Mac_OS_X	7.0.0
>AGDCBacklightControl	5.2.4
>ACPI_SMC_PlatformPlugin	1.0.0
>BridgeAudioCommunication	6.70.7
>!ABacklight	180.3
>!AThunderboltIP	3.1.4
>!AAVEBridge	6.1
>!AFIVRDriver	4.1.0
>!ABridgeAudio!C	6.70.7
>!AGFXHDA	100.1.428
>!A!IPCHPMC	2.0.1
>!ATopCaseHIDEventDriver	3430.1
>!AHIDALSService	1
>!A!ICFLGraphicsFramebuffer	14.0.6
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.14
@filesystems.autofs	3.0
@filesystems.apfs	1412.120.2
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>!AFileSystemDriver	3.0.1
@filesystems.hfs.kext	522.100.5
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
>!ABCMWLANBusInterfacePCIe	1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
|IOSCSIMultimediaCommandsDevice	422.120.3
|IOBD!S!F	1.8
|IODVD!S!F	1.8
|IOCD!S!F	1.8
>!A!BHIDKeyboard	209
>!UAudio	323.1
>!AGraphicsControl	5.2.4
|IOAVB!F	850.1
>!ASSE	1.0
>IOPlatformPluginLegacy	1.0.0
>!AHDA!C	283.15
|IOHDA!F	283.15
@!AGPUWrangler	5.2.4
>!ABacklightExpert	1.1.0
>driverkit.serial	6.0.0
>X86PlatformPlugin	1.0.0
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
>!AActuatorDriver	3440.1
|IONDRVSupport	576.1
>IOPlatformPlugin!F	6.0.0d8
>!AHIDKeyboard	209
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.5f6
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>!ASMBusPCI	1.0.14d1
|IO!BHost!CUARTTransport	7.0.5f6
|IO!BHost!CTransport	7.0.5f6
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
@!AGraphicsDeviceControl	5.2.4
|IOAccelerator!F2	438.5.4
|IOSlowAdaptiveClocking!F	1.0.0
>!ASMBus!C	1.0.18d1
|IOGraphics!F	576.1
>!AThunderboltEDMSink	4.2.3
>!AThunderboltDPOutAdapter	6.2.6
@kext.triggers	1.0
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
>!AXsanScheme	3
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!A!ILpssI2C	3.0.60
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.5f6
|IO!BPacketLogger	7.0.5f6
|IOUSBMass!SDriver	157.121.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by codeHorse87** [comment]
I can report the same behavior but with different parameters
Mac OS 10.15.7 (19H1217)

> panic(cpu 4 caller 0xffffff801d2c0fcf): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.33/bsd/net/content_filter.c, line: 1067
> Backtrace (CPU 4), Frame : Return Address
> 0xffffffa4121c38a0 : 0xffffff801cb1c63d 
> 0xffffffa4121c38f0 : 0xffffff801cc56b25 
> 0xffffffa4121c3930 : 0xffffff801cc486ae 
> 0xffffffa4121c3980 : 0xffffff801cac2a40 
> 0xffffffa4121c39a0 : 0xffffff801cb1bd07 
> 0xffffffa4121c3aa0 : 0xffffff801cb1c0f7 
> 0xffffffa4121c3af0 : 0xffffff801d2c0b3c 
> 0xffffffa4121c3b60 : 0xffffff801d2c0fcf 
> 0xffffffa4121c3b70 : 0xffffff801ced7f1e 
> 0xffffffa4121c3bb0 : 0xffffff801ced7c07 
> 0xffffffa4121c3bd0 : 0xffffff801ced6c02 
> 0xffffffa4121c3c20 : 0xffffff801ced354e 
> 0xffffffa4121c3c80 : 0xffffff801d05a5a9 
> 0xffffffa4121c3cd0 : 0xffffff801d0d234b 
> 0xffffffa4121c3df0 : 0xffffff801d0a6f0c 
> 0xffffffa4121c3e20 : 0xffffff801d0a0500 
> 0xffffffa4121c3ee0 : 0xffffff801d0a02c0 
> 0xffffffa4121c3f40 : 0xffffff801d183cb7 
> 0xffffffa4121c3fa0 : 0xffffff801cac3206 
> 
> BSD process name corresponding to current thread: com.objective-se
> Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev
> 
> Mac OS version:
> 19H1217
> 
> Kernel version:
> Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64
> Kernel slide:     0x000000001c800000
> Kernel text base: 0xffffff801ca00000
> __HIB  text base: 0xffffff801c900000
> System model name: MacBookPro16,2 (Mac-5F9802EFE386AA28)
> System shutdown begun: NO
>

**Comment by objective-see** [comment]
This is a known Apple bug 🍎🐛
Yes, LuLu (which runs 100% in user mode) triggers it, but it's an issue in Apple's macOS' kernel code. 

The (only) solution is to upgrade to a version of macOS that is Big Sur (macOS 11) or newer ...as this is where Apple's fixed the issue.
