### ISSUE TITLE
Update notification window looks like malware

### ISSUE THREAD

**Issue by bauermann** [objective-see/LuLu#206]
I just had a big scare today when I logged into the computer: a weirdly-looking window (no title, no icon, no app identification whatsoever) popped up saying "a new version (1.2.2) is avaliable!". A new version of what??? There wasn't even a cancel button, just an update one!

I thought it was some kind of malware trying to goad me into performing some action. I stopped all I was doing to figure out what was going on, and had to resort to a [Python script](https://apple.stackexchange.com/questions/317531/how-to-determine-which-one-process-owns-particular-window) to determine that the message was actually coming from LuLu. That was a big relief!

But it was a very unpleasant experience.

**Comment by objective-see** [comment]
Sorry, this has been fixed ...the update window, was missing the LuLu icon :(

**Comment by bauermann** [comment]
Thanks for fixing it!

Also sorry for filing a duplicate of issue 158. I don't know why I didn't find that issue at the time.
