### ISSUE TITLE
macOS and SMB services

### ISSUE THREAD

**Issue by Piuliss** [objective-see/LuLu#21]
Hi people, 
First of all, a very nice tool I really like it! congrats guys!
I was using the version 0.9.0 of LuLu on my macOS Sierra 10.12.4~6 for several months. 
After I installed it, I started to see awkward behavior when I wanted to connect to a samba service allocated in an Ubuntu 14.04.3, running  as a virtual machine on my computer (with  VMware Fusion),  First, it worked fine, but then when I wanted to connect to SAMBA folder, the connection process got stuck and always showing "connecting... " message. So, I had to disable LuLu and then the connection worked. Even using the GUI (provided by the Finder ) or using the console, the result was the same, it was not connecting. However, after a couple a month, the connection totally got stuck and it disallows me to work with my VM.  Unfortunately, because of that, I had to uninstall LuLu (BTW this process was really painful, even O.S got broken and I had to reset it),I had no option, even  I could not close LuLu (IDK where it is that option). 

Well, I hope you can fix it. I going to wait a while and  I will upgrade my system to High Sierra and I will try again with LuLu

thanks, guys !

**Comment by mrvkino** [comment]
I had the same issue with NFS with my Virtualbox VM using Vagrant. Vagrant was not able to start the NFS mount.

Also, many application where having issue when starting the laptop, this started the efilogin-helper process to load the cpu close to 100% until a restart.

I had to remove it for the time being.

**Comment by sm0kingm4n** [comment]
Same for me, on mac os high sierra 10.13.3 and latest LuLu version 0.9.3.
my NFS and SAMBA shares on home LAN just do not work. Disabling LuLu and re-trying to access shares will work immediately. I wonder if there is a workaround at moment and hoping for a fix. Loving LuLu and I thank you guys for the good work.

**Comment by bhanquier** [comment]
Same: SMB on a TP-Link router, impossible to reach, with "failed to connect" message after about a minute. Disabling LuLu 0.9.3 solved the problem.

**Comment by EnricoMonese** [comment]
Any news on this?

**Comment by alezzblezz** [comment]
Same here, can't access SMB or AFP shares on LAN with LuLu v0.9.4 and OSX 10.13.4

**Comment by macMikey** [comment]
SMB fail going to a MFP.  OSX 10.3.4, LuLu 0.9.4

**Comment by dcava** [comment]
+1 SMB connections fail with what I think is a block on the NetAuthSysAgent. 
See the following console messages:

found matching rule: {
May  5 19:18:38 Davids-MBP-3 LuLu[116]: LuLu(116): sending msg to kext: 'add rule' (pid: 705, action: 1)
May  5 19:18:38 Davids-MBP-3 LuLu[116]: LuLu(116): process start: /System/Library/CoreServices/NetAuthAgent.app/Contents/MacOS/NetAuthSysAgent (705)
May  5 19:18:38 Davids-MBP-3 LuLu[116]: LuLu(116): dequeued new firewall event from kernel (type: 0)
May  5 19:18:38 Davids-MBP-3 LuLu[116]: LuLu(116): processing 'network out' event from kernel queue: 0 /  192.168.1.200
May  5 19:18:40 Davids-MBP-3 LuLu[116]: LuLu(116): couldn't find process (0) in process monitor
May  5 19:18:40 Davids-MBP-3 LuLu[116]: LuLu(116) ERROR: failed to find and/or create process object for 0
May  5 19:18:40 Davids-MBP-3 LuLu[116]: LuLu(116): sending msg to kext: 'add rule' (pid: 0, action: 0)
May  5 19:18:41 Davids-MBP-3 LuLu[116]: LuLu(116): dequeued new firewall event from kernel (type: 1)

**Comment by dcava** [comment]
Adding allow rule for NetAuthSysAgent and NetAuthAgent doesn't seem to fix things, but the error changes....

May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): found matching rule: {
	    action = 1;
	    signingInfo =     {
	        signatureStatus = 0;
	        signedByApple = 1;
	        signingAuthorities =         (
	            "Software Signing",
	            "Apple Code Signing Certification Authority",
	            "Apple Root CA"
	        );
	    };
	    type = 1;
	    user = 0;
	}
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): sending msg to kext: 'add rule' (pid: 857, action: 1)
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): process start: /System/Library/CoreServices/NetAuthAgent.app/Contents/MacOS/NetAuthSysAgent (857)
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): determing code signing flags for /System/Library/CoreServices/NetAuthAgent.app/Contents/MacOS/NetAuthSysAgent/(null)
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): generating code signing info for NetAuthSysAgent (857) with flags: 13
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): done generating code signing info
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): found matching rule: {
	    action = 1;
	    signingInfo =     {
	        signatureStatus = 0;
	        signedByApple = 1;
	        signingAuthorities =         (
	            "Software Signing",
	            "Apple Code Signing Certification Authority",
	            "Apple Root CA"
	        );
	    };
	    type = 3;
	    user = 501;
	}
May  5 19:31:21 Davids-MBP-3 LuLu[116]: LuLu(116): sending msg to kext: 'add rule' (pid: 857, action: 1)
May  5 19:31:23 Davids-MBP-3 LuLu[116]: LuLu(116): dequeued new firewall event from kernel (type: 1)

**Comment by alezzblezz** [comment]
Just FYI, I managed to access AFP on LAN using Path Finder by authorizing nmblookup process

**Comment by flipphillips** [comment]
Noticed this today when using MS Teams - it tries to connect via SMB, apparently, to the college's SharePoint. Had to disable LuLu to get connected. Trying to keep an eye on which process it is invoking,

**Comment by balintbabics** [comment]
I just started using MacOS and LuLu as well and now I noticed I can't able to connect to my NAS's shared folders.

**Comment by objective-see** [comment]
The latest release (0.9.5) fixed this issue!
In short, traffic such as SMB (which originates in the kernel) is now allowed by default. 

Tested this and 
a) confirmed older versions of LuLu wouldn't allow one to connect for example to other shared folders
b) confirmed new version of LuLu no longer breaks this functionality - allowing these connections :)

**Comment by Piuliss** [comment]
Wonderful! Thanks !

**Comment by laimison** [comment]
@objective-see what was the change in code? Having a diff may point me to right direction. Unfortunately, I can't upgrade Mojave to newer version so looking how to allow kernel_task PID 0 via Lulu 1.2.3. I found that with `sudo tcpdump -i any -n -k NP`.

**Comment by laimison** [comment]
Anyway, it seems allowing bunch of stuff helped. Haven't verified what exactly helps, but here is the list:

/usr/bin/smbutil
/sbin/mount_smbfs
/usr/bin/nslookup
Utilities/AirPort Utility
backupd from /System/Library/CoreServices
backupd-helper from /System/Library/CoreServices

I had an issue when Time Machine backup works to remote smb aka Samba, but "Verify Backups" function immediately fails.
"Verify Backups" is visible when you click on Time Machine icon in menu bar by holding ALT button.
