### ISSUE TITLE
Developer name showing as Placeholder Developer

### ISSUE THREAD

**Issue by stuartjash** [objective-see/LuLu#216]
When clicking 'Allow' in the Security & Privacy, I receive a list of developers to approve. None appear to be related to Objective-See. After approving the one that says "Placeholder Developer", I received the pop-up to approve Lulu as a Network filter.

**Comment by objective-see** [comment]
This is (surely) and Apple bug 😅
...as LuLu (or any app), cannot influence the System and Privacy app/list of devs to approve.

**Comment by objective-see** [comment]
Ah, yes - confirmed Apple bug. And apparently now fixed?
https://developer.apple.com/forums/thread/130056

"This is a bug in the OS (FB7621320). We believe it’s fixed in the latest macOS 11.0b3 seed."
