### ISSUE TITLE
Xcode not classified as Apple software

### ISSUE THREAD

**Issue by torarnv** [objective-see/LuLu#218]
![image](https://user-images.githubusercontent.com/7536/94125762-17047780-fe57-11ea-842f-60cf413abb63.png)

Not sure why. Not a big deal, just thought I'd report it :)

**Comment by objective-see** [comment]
Ah, as it's technically from the App Store (vs. an Apple System binary/app).

Regardless, I've update LuLu to also classify such apps as Apple Software.

**Comment by torarnv** [comment]
Ah, makes sense! Thanks!!
