### ISSUE TITLE
LuLu 2.0.0 Restart stays open in Launchpad

### ISSUE THREAD

**Issue by big610** [objective-see/LuLu#219]
LuLu 2.0.0 BETA Restart stays open in Launchpad,
requires closing on each Restart, unlike previous versions. Preferences has no adjustment setting.
Tested on Catalina 10.15.6.

**Comment by objective-see** [comment]
Just to be clear, the Uninstaller app is re-launched? (when you reboot or re-login?) 
Or if it's something else, can you add some more details/and or screen shots! (I wasn't sure what "Restart stays open in Launchpad" was referring too).

Thanks!!

**Comment by big610** [comment]
When I Restart... Coming back on LuLu sits in Launchpad, requiring to be closed. Version 1's did not require closing LuLu; LuLu did it automatically. I don't see anything in Preferences to adjust. See Screenshot: 
[Uploading Screen Shot Launchpad after Restart....png…]()

**Comment by gabrielmaldi** [comment]
Can confirm this behavior.

(Thanks for LuLu 2.0.0, it's great! ❤️).

**Comment by objective-see** [comment]
Thanks for your response! 
...helped me track down and fix the bug. 

The latest beta (https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip) no longer suffers from this issue.
If you can download/test this to confirm the fix, that'd be great!

**Comment by big610** [comment]
Latest beta, fixes Restart with nothing in Launchpad. Instead you on Restart LuLu's Extension Approval Required banner requires closing.
![Screen Shot Extension](https://user-images.githubusercontent.com/35133409/94380289-a9fc1680-00d0-11eb-8143-110dd7e6182b.png)
Menu Bar Icon missing, your choice if you want it or not. I can access by opening app inside Launchpad. But when open all categories are blank. Catalina 10.15.7. Mahalo for your continued time & labor.
![Screen Shot All](https://user-images.githubusercontent.com/35133409/94380297-b54f4200-00d0-11eb-87c1-3d8b8088c30b.png)

**Comment by big610** [comment]
While your looking at code for the Menu Bar, what would be ideal is for the LuLu Menu Bar Icon to have your Green Caterpillar color 93C13C, instead being Black. Colored you stand out, easier for us to pay attention versus being Black with most everything else, Apple items.
![Menu Bar Apps with Color](https://user-images.githubusercontent.com/35133409/94381406-f8abaf80-00d4-11eb-82e6-f2498e333e0f.png)

**Comment by objective-see** [comment]
Thanks! Will look into this.

...yes, if you replace the application with a new version you may have to (re) approve the extension ...thanks Apple :\
And until you do, the extension (which manages the rules), won't be allowed to run ...hence no rules sent to the client (for the UI table).

I'll work on making this more clear (in the alert, etc). 

Can you confirm that once you approve the (new) extension everything is happy? (might have to quit LuLu to restart it). 

If not, can you run the following command from the terminal to gather debug output?
`log stream --level debug --predicate="subsystem='com.objective-see.lulu'"`

Thanks!

**Comment by big610** [comment]
I can't Quit today's version since not in Menu Bar. Could disable from Login Items, then restart?
Terminal command equals dquote> I have DB Browser for SQLite installed if needed.

**Comment by rebelcode-xr** [comment]
I had the same issue but with the latest BETA seems fixed! ;)

**Comment by gabrielmaldi** [comment]
> Thanks for your response!
> ...helped me track down and fix the bug.
> 
> The latest beta (https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip) no longer suffers from this issue.
> If you can download/test this to confirm the fix, that'd be great!

Everything working fine in this release. Thanks!
