### ISSUE TITLE
Endless loop when trying to connect to localhost

### ISSUE THREAD

**Issue by MichaPie** [objective-see/LuLu#22]
When my processes tried to connect to 127.0.0.1 (a local proxy) instead of the internet, the Lulu alert window poped up again and again no matter what button I pressed. The only way to stop this endless loop was to force quit the Lulu deamon and the lulu helper process.
This does only happen sometimes though...

**Comment by objective-see** [comment]
Thanks for reporting!
Recent versions of LuLu now have improved logic to ensure only one alert per process is shown.
