### ISSUE TITLE
"trying to connect to.." string can be *very* long and doesn't wrap

### ISSUE THREAD

**Issue by bmironer** [objective-see/LuLu#220]
This gives a VERY wide window that you have to move manually to dismiss...
example : Twitter and internal api.twitter.com/... urls when using 'endpoint' settings

**Comment by objective-see** [comment]
Ah good catch!
...just fixed 👍  (will push out new beta shortly)

![image](https://user-images.githubusercontent.com/11327812/94222982-86e02580-fe8a-11ea-80c8-bd0ab94673af.png)

**Comment by objective-see** [comment]
Latest beta, now available for download fixes this issue: https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip
