### ISSUE TITLE
In rule editor, the executable path is editable but not selectable

### ISSUE THREAD

**Issue by bmironer** [objective-see/LuLu#223]
So I need to delete it manually character by character instead of cmd-a, to replace the path by a * 
(essentially for port 53)

**Comment by objective-see** [comment]
You can double-click to select (all):
![image](https://user-images.githubusercontent.com/11327812/94406830-527c9b80-010e-11eb-92cd-a1cb07cfc012.png)

That having been said, I'm working to add support for shortcut keys (⌘+a, ⌘+w, etc) - as agreed, that would be nice to have!

**Comment by bmironer** [comment]
triple-click actually, (double click selects the whole word)
thanks for the tip, I forgot about that one
