### ISSUE TITLE
Allow wildcard or 'localhost' in rules to all local ips

### ISSUE THREAD

**Issue by bmironer** [objective-see/LuLu#224]
used to allow port 53 for all programs on all local interfaces for example

**Comment by objective-see** [comment]
Via the add rule's window, you can create wildcard rule ("*") to apply to all processes :)

![image](https://user-images.githubusercontent.com/11327812/94508561-e5b8de00-01ad-11eb-854e-a8a131586786.png)

![image](https://user-images.githubusercontent.com/11327812/94508570-e9e4fb80-01ad-11eb-9765-deda2578f1d5.png)

**Comment by bmironer** [comment]
Yes but what about the address?
* would allow any host and 127.0.0.1 wouldn't match programs calling dns on the actual local interface ip

**Comment by objective-see** [comment]
Ah, all localhost IPs are allowed:

```
//ignore traffic destined for localhost
if( (YES == [remoteEndpoint.hostname hasPrefix:@"::1"]) ||
     (YES == [remoteEndpoint.hostname isEqualToString:@"127.0.0.1"]) )
    {
       //log msg
       os_log_debug(logHandle, "ignoring 'localhost' traffic");
          
       //bail
       goto bail;
    }
```

If you're seeing alerts with localhost addrs/endpoints, lmk!

**Comment by bmironer** [comment]
You're right. 
I mixed up the ipv6 addresses of my machine and my router. Same prefix obviously.
Sorry for the confusion.
