### ISSUE TITLE
Python executables request the same authorization repeatedly

### ISSUE THREAD

**Issue by bmironer** [objective-see/LuLu#234]
for example 
when using 'youtube-dl' to download a video, 
the same rule for https://www.youtube.com/watch?v=CaAY-jAjm0w&feature=emb_logo is added 12 times

**Comment by bmironer** [comment]
additionaly in the rules windows, these 12 rules are merged with the rules for the embedded Python exec in GOG Galaxy under the same 'org.python.python' id, although it's at a completely different path...

**Comment by objective-see** [comment]
Thanks for the bug report! 
Having a bit of trouble replicating :/ 

Can you:
1. Confirm you're using the [latest beta](https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip)
...might have to manually (re)install it, as the I just pushed out a new version (at the same URL) a day or so ago.

2. Provide the version of macOS 

3. Provide any relevant output from running the following in the terminal: 
`log stream --level debug --predicate="subsystem='com.objective-see.lulu'"`

4. Any other details? 
...did you click allow to allow any connections for the Python process? or select the remote endpoint option?

5. Anything else to help reproduce? (i.e. exact steps / commands you executed)
In the below image, I ran: `youtube-dl "www.youtube.com/watch?v=CaAY-jAjm0w"`
...which generated a single LuLu alert. Once I reacted to said alert (allowed), no other alert was shown ...
![image](https://user-images.githubusercontent.com/11327812/95400816-50050900-08a7-11eb-9df3-7be6b207df5f.png)

Thanks!

**Comment by bmironer** [comment]
OK, so here's what I found, it's a bit convoluted and I believe there are multiple issues : 

- I was running the latest beta (same creation date), on Cataline 10.15.7
- I always used allow / process / always for these tests

- I removed all the python rules first (using the search bar for 'Python' in all rules)
- I tried youtube-dl again : no issues (allowed once and done)
- then I tried fiddling a bit more by launching all the python-related software I had used lately
namely Visual Studio Code (including a bunch of extensions for python env)
and GOG Galaxy 2.0 (which I find a bit aggressive in its installation process btw)

I couldn't reproduce the bug at first...
until GOG Galaxy started asking repeatedly to allow Python too!
(but youtube-dl stayed fine)

I removed the Python rules once more and tried the other way : GOG first then youtube-dl, 
to see if youtube-dl would be affected

Then, no popups anymore : python rules were all deleted, but python wasn't blocked at all anymore!!
youtube-dl, vscode, gog, would all work fine, with no Python rules in Lulu!!

Then I Uninstalled Lulu (from the Lulu menu), reinstalled the beta (redownloaded today), and rebooted.

No rules at all at startup, so I re-enabled the basics

Tried youtube-dl : allowed once and done

Tried GOG : multiple popups!!, and GOG ended crashing!

I did it once more while logging, with youtube-dl, GOG and vscode running (see log file attached)

I also noticed that the "Python" item in the rule list has multiple completely unrelated paths
even with different versions (system Python is 2.7, GOG uses an internal python 3.7 runtime, and vscode was using brew's python@3.8)
I believe these should really by considered as different executables and not merged in the list (but that's just for display I guess?)
or maybe add the path in the rules list above the address::port ?

see screenshots below with the paths and the repeated rules for GOG


Best regards, and good luck...

Let me know if I can test anything.

Ben

**Comment by bmironer** [comment]
Python 3.9 just appeared!
And now brew python@3.8 and python@3.9 both appear twice : once on they own section under (their own path), and once merged with all the python executables under (org.python.python)

Oh also when double clicking on the section, opens the sheet with all the paths but sometimes it reopens by itself and the close button doesn't work (it just beeps), but command-w does

**Comment by objective-see** [comment]
Thanks for the details, super helpful! 
In short, LuLu couldn't handle apps that had the same code signing id (i.e. `org.python.python` signed by multiple dev ids).

I've updated the code so that rules are now key'd by a combo of the signing id + the signer ...to handle this. 
The rules's window now also shows the signing id / signer (or just path of the item if it's unsigned). 

Note however, this means rules are *not* compatible with older betas!
Can you test the latest beta (after uninstalling the current/any beta you have installed)? 

latest beta: [https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip](https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip)

Thanks!

**Comment by bmironer** [comment]
That's much better indeed. Couldn't reproduce the issue.
However I've a found few minor ones : 
- when a non authorized program starts it can popup multiple windows for the same rule (multiple connections or retries I guess), but if you allow them all, you've got duplicated rules.
- Is the path shown in rules under process name the last one to have matched? (it seems to, on Any Process rules especially)
- Is there a keyboard shortcut for quick allow / deny ? (It seems cmd-w defaults to allow all on the popup?)

**Comment by objective-see** [comment]
great! 
...yes, just noticed the (multiple popups) windows. Fix will be out for that shortly.

**Comment by objective-see** [comment]
Ok, just updated the beta (again): [https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip](https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0_BETA.zip)

...should address the "multiple alerts per process" issue 😅

Under the process name is either:
a) the code signing id and code signer (if signed by an developer id, or app store)
b) the process path if the item is unsigned

Note there can be multiple same process names, however, either the code-signing info, or process path will be different. 

No shortcut yet for the alerts, but that's a good idea!
