### ISSUE TITLE
Lulu 2.0 (beta) - minimum OS 10.15?

### ISSUE THREAD

**Issue by supervisitor** [objective-see/LuLu#243]
A security tool should be at least for all supported operating system versions (currently 10.13.6 - 10.15.7). This will ensure that the user's entire infrastructure is covered with the same tool on all machines.
Or maybe even more versions (10.11-10.15?). This ensures that even older systems can be secured with the same tool... but this section is now really product policy.
In any case, not only the marketing dream of Apple: all of them use only the latest 10.15.

At least the installer of current beta requires minimum version 10.15, so I'm out of now... a sad thing.

**Comment by objective-see** [comment]
Previous versions of LuLu work on macOS 10.12+
You can download the latest of such version here: [v1.2.3](https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.2.3.zip)

The reason that version 2.0+ is only compatible with macOS 10.15+, is that the **Apple** frameworks/APIs it leverages are only available on 10.15+ (System Extension APIs, etc).  ..If Apple makes those frameworks available to older versions of macOS, then LuLu v2.0 would be able to run on them as well!

**Comment by supervisitor** [comment]
@objective-see 
first: nice app, thanks for, and I respect your decision... but... 😇  you have to choose if you want to follow the Apple dictat and go the way to support a system 10.15 only infrastructure?
you should remember the users of 10.14 and think about if this frameworks are really needed. I talk to you, now you have to talk with Apple... 😎  and yes, I'm in contact with Apple to discuss this on different path, too.
