### ISSUE TITLE
LuLu 2.0.0 breaks Siri and dictation

### ISSUE THREAD

**Issue by trendchiller** [objective-see/LuLu#244]
I run MacOS Catalina (latest version)
When LuLu 2.0.0 is active, Siri and dictation do not work - they show the microphone, but there is no reaction when I speak.
Deactivating LuLu solves this problem.
I uninstalled LuLu 2.0.0 and installed LuLu 1.2.3 and the probes is gone, so there seems to be a rule or else, that filters Siri or dictation connectivity.
Voice Assist still works and the dictation microphone test also works.

**Comment by simonf00** [comment]
I see the same behaviour. When Lulu is active, the Siri microphone is not active. When Lulu is disabled, Siri works as expected.

**Comment by Chasapple4** [comment]
In Lulu preferences is there rules for Siri?

**Comment by trendchiller** [comment]
Did not see any, but apple services are allowed, so Siri should be included ?

**Comment by simonf00** [comment]
Just installed the latest beta and Siri is working again.

**Comment by objective-see** [comment]
as noted by @simonf00 ...appears latest beta fixes this.

**Comment by dchristofzik** [comment]
Where do i get latest beta version? With the 2.0.0 i found problem isn't solved.

**Comment by trendchiller** [comment]
https://bitbucket.org/objective-see/deploy/downloads/LuLu_2.0.0.dmg
This works for me ;-)

**Comment by dchristofzik** [comment]
Not for me 

Same behavior as descripted before.

Thanks

David

**Comment by Chasapple4** [comment]
> Not for me Same behavior as descripted before. Thanks David
> […](#)

Check if Lulu is prompting for out going new connections (there are a few for Siri and dictation)
