### ISSUE TITLE
Big Sur Public release 11.0.1. cannot block / deny any Apple services

### ISSUE THREAD

**Issue by zaphodd** [objective-see/LuLu#246]
Big Sur Public release 11.0.1.   
I Installed new 'Big Sur' today and i cannot find a way to upload my saved rules.plist from earlier version of Lulu i used. 

Also have to manually enable the system extension on every boot. and i can't block / deny any Apple services except ones i have just installed. i want option to block anything i want.

SIP is disabled to allow me to try to use LuLu

**Comment by ulfklose** [comment]
https://twitter.com/patrickwardle/status/1318465421796782082

**Comment by zaphodd** [comment]
Thankyou.
it looks like a BSD or Linux OS in the near future on this Apple hardware.
How disappointing of Apple
Good Luck
