### ISSUE TITLE
LULU bypass issue?

### ISSUE THREAD

**Issue by coder7867** [objective-see/LuLu#263]
The version doesn't matter, but some people seem to post how to bypass the firewall

Here is the website telling steps to bypass LuLu: 

https://null-byte.wonderhowto.com/how-to/hacking-macos-bypass-lulu-firewall-with-google-chrome-dependencies-0198675/

I haven't tested but is this issue fixed?

**Comment by objective-see** [comment]
Yes (or it should be!)
...LuLu now uses items code-signing ids ...thus if a trusted/approved item is modified, the code signing info should change, and LuLu will see it as a "new" item and alert the user.
