### ISSUE TITLE
Your computer restarted because of a problem

### ISSUE THREAD

**Issue by big610** [objective-see/LuLu#267]
Your computer restarted because of a problem. 

panic(cpu 3 caller 0xffffff801dabf74f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2.2/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 3), Frame : Return Address
0xffffff913eb8b8a0 : 0xffffff801d31868d 
0xffffff913eb8b8f0 : 0xffffff801d452ab5 
0xffffff913eb8b930 : 0xffffff801d44463e 
0xffffff913eb8b980 : 0xffffff801d2bea40 
0xffffff913eb8b9a0 : 0xffffff801d317d57 
0xffffff913eb8baa0 : 0xffffff801d318147 
0xffffff913eb8baf0 : 0xffffff801dabf2bc 
0xffffff913eb8bb60 : 0xffffff801dabf74f 
0xffffff913eb8bb70 : 0xffffff801d6d542e 
0xffffff913eb8bbb0 : 0xffffff801d6d5117 
0xffffff913eb8bbd0 : 0xffffff801d6d4112 
0xffffff913eb8bc20 : 0xffffff801d6d0a5e 
0xffffff913eb8bc80 : 0xffffff801d858e19 
0xffffff913eb8bcd0 : 0xffffff801d8d0b3b 
0xffffff913eb8bdf0 : 0xffffff801d8a56fc 
0xffffff913eb8be20 : 0xffffff801d89ecf0 
0xffffff913eb8bee0 : 0xffffff801d89eab0 
0xffffff913eb8bf40 : 0xffffff801d982437 
0xffffff913eb8bfa0 : 0xffffff801d2bf206 

BSD process name corresponding to current thread: com.objective-se

Mac OS version:
19H15

It's been happening all the time, with 2.0.0.

**Comment by pieterjoanUvA** [comment]
Having the exact same problem, see osx-dump-snippet

`panic(cpu 2 caller 0xffffff80098bf74f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2.2/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 2), Frame : Return Address
0xffffff81f36bb8a0 : 0xffffff800911868d 
0xffffff81f36bb8f0 : 0xffffff8009252ab5 
0xffffff81f36bb930 : 0xffffff800924463e 
0xffffff81f36bb980 : 0xffffff80090bea40 
0xffffff81f36bb9a0 : 0xffffff8009117d57 
0xffffff81f36bbaa0 : 0xffffff8009118147 
0xffffff81f36bbaf0 : 0xffffff80098bf2bc 
0xffffff81f36bbb60 : 0xffffff80098bf74f 
0xffffff81f36bbb70 : 0xffffff80094d542e 
0xffffff81f36bbbb0 : 0xffffff80094d5117 
0xffffff81f36bbbd0 : 0xffffff80094d4112 
0xffffff81f36bbc20 : 0xffffff80094d0a5e 
0xffffff81f36bbc80 : 0xffffff8009658e19 
0xffffff81f36bbcd0 : 0xffffff80096d0b3b 
0xffffff81f36bbdf0 : 0xffffff80096a56fc 
0xffffff81f36bbe20 : 0xffffff800969ecf0 
0xffffff81f36bbee0 : 0xffffff800969eab0 
0xffffff81f36bbf40 : 0xffffff8009782437 
0xffffff81f36bbfa0 : 0xffffff80090bf206 

BSD process name corresponding to current thread: com.objective-se

Mac OS version:
19H15

Kernel version:
Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
Kernel UUID: 9B5A7191-5B84-3990-8710-D9BD9273A8E5
Kernel slide:     0x0000000008e00000
Kernel text base: 0xffffff8009000000
__HIB  text base: 0xffffff8008f00000
System model name: MacBookPro9,1 (Mac-4B7AC7E43945597E)
System shutdown begun: NO
Panic diags file available: YES (0x0)`

This was my first occasion.

**Comment by objective-see** [comment]
Thanks for the bug report
...this is the same issue as [Issue #264 257](https://github.com/objective-see/LuLu/issues/257)

After digging, it appears to be an issue in Apple's kernel code (albeit triggered by LuLu).

As such, after talking to some folks at Apple, I've submitted an official bug report to Apple.
...mahalo for your patience, hope they will push out a fix soon. Will keep you updated.

**Comment by Haleclipse** [comment]
looking forward to solving the problem.

**Comment by nujabse** [comment]
Look like we can only wait until Apple releases a fix for this

**Comment by fabioz23** [comment]
i've the same problem on MBP16 with latest macos 11.1
resetting SMC and NVRAM as suggested on some forums is useless

**Comment by fabioz23** [comment]
@objective-see : i've updated LuLu at 2.1.0 on macOS 11.1 = same problem.
Updating also macOS to 11.2 beta the problem seems to be disappeared. After wake the OS ask for login and there aren't reboot with crash reports.

**Comment by objective-see** [comment]
I know Apple has made a myriad of improvements in macOS 11.2 (beta).
...thanks too your testing, sounds like a fix from them is forthcoming in that release! 🤞

**Comment by fabioz23** [comment]
I confirm that with 11.2 the macbook is more reactive, especially on waking up after opening the lid.

**Comment by big610** [comment]
Version 2.3.0. This occurrence happened while in sleep mode.

Your computer was restarted because of a problem.
[code]
panic(cpu 2 caller 0xffffff8006cc065f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.16/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 2), Frame : Return Address
0xffffff9126e5b8a0 : 0xffffff800651963d 
0xffffff9126e5b8f0 : 0xffffff8006653ae5 
0xffffff9126e5b930 : 0xffffff800664566e 
0xffffff9126e5b980 : 0xffffff80064bfa40 
0xffffff9126e5b9a0 : 0xffffff8006518d07 
0xffffff9126e5baa0 : 0xffffff80065190f7 
0xffffff9126e5baf0 : 0xffffff8006cc01cc 
0xffffff9126e5bb60 : 0xffffff8006cc065f 
0xffffff9126e5bb70 : 0xffffff80068d688e 
0xffffff9126e5bbb0 : 0xffffff80068d6577 
0xffffff9126e5bbd0 : 0xffffff80068d5572 
0xffffff9126e5bc20 : 0xffffff80068d1ebe 
0xffffff9126e5bc80 : 0xffffff8006a59c99 
0xffffff9126e5bcd0 : 0xffffff8006ad1a3b 
0xffffff9126e5bdf0 : 0xffffff8006aa65fc 
0xffffff9126e5be20 : 0xffffff8006a9fbf0 
0xffffff9126e5bee0 : 0xffffff8006a9f9b0 
0xffffff9126e5bf40 : 0xffffff8006b83347 
0xffffff9126e5bfa0 : 0xffffff80064c0206 

BSD process name corresponding to current thread: com.objective-se
[/code]
Mac OS version:
19H524

Apple is making your life too difficult.

**Comment by waveman777** [comment]
Happened to me yesterday. MacOS Catalina, Lulu 2.0.0

`panic(cpu 5 caller 0xffffff800f6c065f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.16/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 5), Frame : Return Address
0xffffff92225138a0 : 0xffffff800ef1963d 
0xffffff92225138f0 : 0xffffff800f053ae5 
0xffffff9222513930 : 0xffffff800f04566e 
0xffffff9222513980 : 0xffffff800eebfa40 
0xffffff92225139a0 : 0xffffff800ef18d07 
0xffffff9222513aa0 : 0xffffff800ef190f7 
0xffffff9222513af0 : 0xffffff800f6c01cc 
0xffffff9222513b60 : 0xffffff800f6c065f 
0xffffff9222513b70 : 0xffffff800f2d688e 
0xffffff9222513bb0 : 0xffffff800f2d6577 
0xffffff9222513bd0 : 0xffffff800f2d5572 
0xffffff9222513c20 : 0xffffff800f2d1ef7 
0xffffff9222513c80 : 0xffffff800f459c99 
0xffffff9222513cd0 : 0xffffff800f4d1a3b 
0xffffff9222513df0 : 0xffffff800f4a65fc 
0xffffff9222513e20 : 0xffffff800f49fbf0 
0xffffff9222513ee0 : 0xffffff800f49f9b0 
0xffffff9222513f40 : 0xffffff800f583347 
0xffffff9222513fa0 : 0xffffff800eec0206 

BSD process name corresponding to current thread: com.objective-se

Mac OS version:
19H524

Kernel version:
Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
Kernel UUID: 64F23D6D-4C30-3FC4-B7C2-9EE0BBA0D29A
Kernel slide:     0x000000000ec00000
Kernel text base: 0xffffff800ee00000
__HIB  text base: 0xffffff800ed00000
System model name: MacBookPro11,4 (Mac-06F11FD93F0323C5)
System shutdown begun: NO
Panic diags file available: YES (0x0)`

**Comment by objective-see** [comment]
This does seem to have been fixed by Apple, in the latest version of Big Sur (11.2) ...but is unlikely to be back ported to Catalina :(

**Comment by big610** [comment]
Your computer was restarted because of a problem, is happening very frequently now.
For a Catalina solution do you recommend going back to LuLu 1.2.3 ?

**Comment by big610** [comment]
Your computer was restarted because of a problem LuLu 2.3.1 macOS Catalina 10.15.7 19H254, keeping update with the current most Apple Security Updates.
First 2.3.1 occurrence, found while was in sleep mode.
Any suggestion's go back to LuLu 1.2.3? But that was designed for older Security Updates?

panic(cpu 1 caller 0xffffff80116c065f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.16/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 1), Frame : Return Address
0xffffff9132a238a0 : 0xffffff8010f1963d 
0xffffff9132a238f0 : 0xffffff8011053ae5 
0xffffff9132a23930 : 0xffffff801104566e 
0xffffff9132a23980 : 0xffffff8010ebfa40 
0xffffff9132a239a0 : 0xffffff8010f18d07 
0xffffff9132a23aa0 : 0xffffff8010f190f7 
0xffffff9132a23af0 : 0xffffff80116c01cc 
0xffffff9132a23b60 : 0xffffff80116c065f 
0xffffff9132a23b70 : 0xffffff80112d688e 
0xffffff9132a23bb0 : 0xffffff80112d6577 
0xffffff9132a23bd0 : 0xffffff80112d5572 
0xffffff9132a23c20 : 0xffffff80112d1ebe 
0xffffff9132a23c80 : 0xffffff8011459c99 
0xffffff9132a23cd0 : 0xffffff80114d1a3b 
0xffffff9132a23df0 : 0xffffff80114a65fc 
0xffffff9132a23e20 : 0xffffff801149fbf0 
0xffffff9132a23ee0 : 0xffffff801149f9b0 
0xffffff9132a23f40 : 0xffffff8011583347 
0xffffff9132a23fa0 : 0xffffff8010ec0206 

BSD process name corresponding to current thread: com.objective-se

Mac OS version:
19H524

Do you need the full report?

**Comment by seathasky** [comment]
a year later and still is still occuring. GG Apple

**Comment by Rhys-T** [comment]
I was using LuLu a while back on this Catalina installation[^version], and I don't remember ever having this problem. I had to take it out at the time because of an unrelated issue (which seems to be gone now), but recently started trying it again (at version 2.4.3), and have now had this exact kernel panic twice (fairly far apart, but still…). Even if the bug is in Apple's code, could the older version have been behaving differently enough that it managed to avoid triggering it - and could it be made to do so again? Or was I just lucky before? (This GitHub issue does seem to have been opened prior to my first attempt at using LuLu…)

Is there anywhere we can find more info about what the bug actually was/is?

[^version]: I'm pretty sure it was a 2.x version of LuLu. The earliest I have in my Downloads is 2.4.1, but it's possible I had an older one and deleted it at some point.

**Comment by objective-see** [comment]
This is a known Apple bug 🍎🐛
Yes, LuLu (which runs 100% in user mode) triggers it, but it's an issue in Apple's macOS' kernel code. 

The (only) solution is to upgrade to a version of macOS that is Big Sur (macOS 11) or newer ...as this is where Apple's fixed the issue.
