### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ghost** [objective-see/LuLu#27]
Hi,

Probably asking for a lot, but was just wondering if this is planned for the future?

Thanks :)

**Comment by maxxer** [comment]
A little OT, but there's [OpenSnitch](https://www.opensnitch.io/)

**Comment by rjzak** [comment]
Similar: http://douaneapp.com

**Comment by objective-see** [comment]
sorry, not at the moment 😔  - mostly as LuLu makes use of a ton of macOS-specific frameworks, code, logic, etc...so basically would have to be fully re-written for Linux
