### ISSUE TITLE
'Filter Rule' Searchbox does not allow [backspace-key] deletion 

### ISSUE THREAD

**Issue by nousr** [objective-see/LuLu#277]
- MacOs Catalina 10.15.7 
- Installed via binary on official website 

Steps to reproduce:
1. open LuLu rules via status bar
2. select 'All Rules' tab
3. type something in search bar
4. try to use backspace to delete characters 

If you point me in the right direction (where this problem may be solved in the source code) I'd be happy to submit a quick fix. Otherwise, hopefully it can be added to a future change list.

**Comment by objective-see** [comment]
Thanks for bug report!
...fixed in v2.1.0 :)
