### ISSUE TITLE
sudo: configure.sh: command not found

### ISSUE THREAD

**Issue by saikiran91** [objective-see/LuLu#28]
MacBook-Pro:LuLu_0 pai$ sudo configure.sh -install
Password:
sudo: configure.sh: command not found
MacBook-Pro:LuLu_0 pai$ sudo configure.sh -install
sudo: configure.sh: command not found
MacBook-Pro:LuLu_0 pai$ sudo configure.sh -install
sudo: configure.sh: command not found
MacBook-Pro:LuLu_0 pai$ sudo configure.sh -install
sudo: configure.sh: command not found
MacBook-Pro:LuLu_0 pai$ sudo configure.sh -install
sudo: configure.sh: command not found
MacBook-Pro:LuLu_0 pai$

**Comment by voidref** [comment]
> Build LuLu or download the pre-built binaries/components from the Releases page, then execute the configuration script

**Comment by voidref** [comment]
Additionaly . would need to be in your path, try

    $ sudo ./configure.sh -install

**Comment by barischrooneyj** [comment]
or try `brew cask install lulu`

**Comment by Strangersworld** [comment]
Now what should I do.

**Comment by objective-see** [comment]
UI-based installer now supersedes the `configure` script :)
![installer](https://objective-see.com/images/LL/installApp.png)

**Comment by MohammedAlzard** [comment]
sudo sh configure.sh -install
