### ISSUE TITLE
Internet not accessible from Chrome & other apps even they whitelisted

### ISSUE THREAD

**Issue by KashifHK123** [objective-see/LuLu#286]
System: MacOS Catalina 10.15.6
LuLu: v2.0
Description: Internet works fine if disable Lulu firewall , when I enable Lulu firewall internet not accessible from chrome and other apps even they allowed/enabled from lulu rules. the custom port also not reachable from a browser like Cpanel 2083 or 2087 etc.

**Comment by justauserid** [comment]
> As Apple continues to improve the stability of this framework, it is recommended you upgrade to the latest version of macOS 11 (Big Sur), before installing LuLu. 

....

> Looking for an older version (compatible with older versions of macOS)?

> Download: LuLu (v1.2.3). 

https://objective-see.com/products/lulu.html

**Comment by KashifHK123** [comment]
Yes, it Works Fine in macOS 11 Big Sur.
