### ISSUE TITLE
Add M1 Mac support

### ISSUE THREAD

**Issue by F3000** [objective-see/LuLu#288]
When it's not already done please add M1 native support

**Comment by J3n50m4t** [comment]
It works perfectly fine for me on MacOS 11.1 with a MacBook Pro 13" M1.
Silicon Support would be fine though  
<img width="493" alt="Bildschirmfoto 2020-12-30 um 22 03 42" src="https://user-images.githubusercontent.com/13681191/103381042-e5045080-4aea-11eb-90c0-a0b58d994957.png">

**Comment by objective-see** [comment]
Added in v2.1.0
![image](https://user-images.githubusercontent.com/11327812/104279753-e91b6100-544e-11eb-8523-b5b586ad3ad3.png)
