### ISSUE TITLE
Blocklist not effective

### ISSUE THREAD

**Issue by pier611-pm-me** [objective-see/LuLu#291]
The Blocklist mechanism in Lulu does not appear to be effective (when using https://ceadd.ca/blockyouxlist.txt), as it does not prevent access to some the domains listed (e.g. google-analytics.com). Is it me or is this a bug?

**Comment by dkeu** [comment]
Same with me. Does not block access, nor advertising that comes through the addresses. Seems to be completely non-functional.

**Comment by objective-see** [comment]
Aloha!
Thanks for the bug report. 

A few thoughts/questions

1. In previous versions of LuLu, the block list had to be a local file ...not a remote URL (sorry if that wasn't clear!)
Were you specifying a local file? or a remote url? 

However, in version 2.1.0 (just released!) you can now **also** specify a URL, e.g. https://ceadd.ca/blockyouxlist.txt
![image](https://user-images.githubusercontent.com/11327812/104280511-23393280-5450-11eb-885d-6a3dce99d0e0.png)

2. If you run `log stream --level debug --predicate="subsystem='com.objective-see.lulu'"`  from the Terminal,
...do you see anything like the following? (`"client in using block list, will check for match"` or `"block listed item 'googleadservices.com', matches flow url host: googleadservices.com or ip addr: 172.217.14.66"`). 

![image](https://user-images.githubusercontent.com/11327812/104280463-0d2b7200-5450-11eb-9444-c4e575cde43f.png)

3. If you browse directly to a URL in the block list (i.e. `google-analytics.com`) is it not blocked?
![image](https://user-images.githubusercontent.com/11327812/104280539-2f24f480-5450-11eb-9542-22b59d7f7627.png)

Any other info, much appreciated!

**Comment by pier611-pm-me** [comment]
G'day,
Thanks for getting back to me.

In answer - In version 2.0.0:
1. It occurs with both a local file and a URL (the first thing I tried).
2. Yes. This is present in the terminal log output
3. In browsing to google-analytics.com it is not blocked but it is redirected to https://marketingplatform.google.com/about/analytics/. Interestingly, googleadservices.com/ is blocked. Numerus other URL's in the blocklist redirect to another site (true in multiple different browser - with all ad blosking extensions disabled.

In version 2.1.0
Identical to 3 above.

I trust this helps...
