### ISSUE TITLE
Prevent multiple instances of Lulu from running at the same time.

### ISSUE THREAD

**Issue by rhymeswithfleece** [objective-see/LuLu#3]
I am so excited about Lulu! 

Maybe you have noticed this already, but it is possible to have more than one instance of Lulu open at a time. I achieved this by installing Lulu from the command line and then opening the app in Launchpad. Ideally Lulu could detect if more than one instance is running concurrently and kill the extra instance. 

After killing all Lulu processes in Activity Monitor, I could not reproduce the issue.

![lulu2instances](https://user-images.githubusercontent.com/27594456/30409093-e832f4ca-98d0-11e7-99e7-f3eb24d5d8d7.png)

**Comment by objective-see** [comment]
https://github.com/objective-see/LuLu/commit/e0d140f830c071fbef422d60fe5d70906c0fed1d fixes this issue. Code now checks in `main()` for existing instances and bails if it finds any.
