### ISSUE TITLE
Update check failed

### ISSUE THREAD

**Issue by mino98** [objective-see/LuLu#30]
Hi, 
fresh install of LuLu 0.91 on macOS 10.13.2, I noticed that the update check fails.

The UI shows this:
<img width="600" alt="screen shot 2018-01-20 at 15 27 24" src="https://user-images.githubusercontent.com/27546434/35185090-7538103c-fdf6-11e7-8a5e-bfdb363730f8.png">

And I see this in syslog:
`com.objective-see.luluHelper[483]: LULU(483) ERROR: update check failed`

I do see that the agent is contacting `65.60.38.45:443`, completing the TLS handshake but obviously I have no way of knowing what's the server answer...

**Comment by pronouncedJerry** [comment]
Same

**Comment by alvarnell** [comment]
Looks like there's a certificate issue:
![screen shot 2018-01-19 at 10 40 46 pm](https://user-images.githubusercontent.com/4943704/35247542-a92714c6-ff7f-11e7-9a6e-63dc6a55e1d7.png)

**Comment by n0ncetonic** [comment]
Any update on this?

**Comment by objective-see** [comment]
The update code: https://github.com/objective-see/LuLu/blob/790cd977bc13d28846faa0ec41d9299a14e71767/shared/Update.m#L59 ...simply reads a [server-side json file ](https://objective-see.com/products.json) to see if there is a new version.

I just updated this file to include LuLu, and specify its latest version (v.0.9.4) - so update checks should now function as expected - and alert you automatically when a new version is posted.
