### ISSUE TITLE
Consider alternative source-available licenses

### ISSUE THREAD

**Issue by ignoramous** [objective-see/LuLu#303]
I'm aware there's already been a discussion on re-licensing LuLu.

Have you considered software-specific source-available licenses like [Commons Clause](https://commonsclause.com/), [Perimeter](https://polyformproject.org/licenses/), [BSL](https://mariadb.com/bsl11/), or a strong-copyleft like AGPL instead? These licenses make it easy to reason about distribution, code copyright, warranty, liability, patent-use, and so on.

Probably, a MIT License + (Commons Clause or BSL) works best for LuLu?

https://github.com/objective-see/LuLu/issues/4

**Comment by objective-see** [comment]
Thanks for the feedback / suggestions!

LuLu is now fully GPL'd (v3): https://github.com/objective-see/LuLu/commit/4804d0e5445c55f736d873490456c0a9c74fcef5

**Comment by ignoramous** [comment]
> LuLu is now fully GPL'd (v3): `4804d0e`

That's more than what I bargained for. Thanks!
