### ISSUE TITLE
LuLu crashes for processes using non-UTF8 arguments

### ISSUE THREAD

**Issue by xnyhps** [objective-see/LuLu#305]
Process arguments on macOS do not have a defined or enforced encoding. UTF8 is common, but nothing prevents a process from using something non-UTF8.

LuLu (and I suspect some other Objective-See tools too) assumes arguments are UTF8:

https://github.com/objective-see/LuLu/blob/aafab24ac9aa5278d81cacf370e05f9fc6b03681/LuLu/Extension/Process.m#L474-L478

When a C string which is not valid UTF8 is used, `-[NSString stringWithUTF8String:]` returns `nil`. When attempting to add a `nil` object to an `NSMutableArray`, it throws an exception. This exception is not caught, which means the network extension crashes.

After the network extension crashes, internet access is unfiltered for a short time while it restarts. This makes it possible for malware to bypass LuLu by making it crash and then quickly accessing the network.

I recommend fixing this by either ignoring arguments that are invalid UTF8, or using `NSData` for storing arguments.

**Comment by objective-see** [comment]
Thanks! Good catch 😅
...just pushed a commit to fix the issue. Will make it into the next release!

**Comment by objective-see** [comment]
fixed release v2.3.0
