### ISSUE TITLE
Reverse DNS on "LuLu Alert" Window

### ISSUE THREAD

**Issue by julienbordet** [objective-see/LuLu#308]
Could it be possible to perform a reverse dns for ip addresses in the "Lulu Alert" window (network / IP address) ?

![Capture d’écran 2021-01-21 à 16 16 11](https://user-images.githubusercontent.com/12191712/105371334-cd5d4b00-5c04-11eb-84ac-0af4d18e8ad5.png)

Maybe make it optional in the preference settings, as there are reasons not to want it (performance, privacy...)

**Comment by julienbordet** [comment]
BTW the reverse DNS is visible in the Rules window : 
![Capture d’écran 2021-01-21 à 16 23 31](https://user-images.githubusercontent.com/12191712/105371584-085f7e80-5c05-11eb-8cb3-64576e2dd198.png)

**Comment by dcaballero** [comment]
I agree with this request, I do understand you can see the reverse dns info in the rules window, but it would be extremely useful in the notification to help decide whether to allow a connection or not.
If in the alert I see an IP, it doesn't help me, but if I see a domain name that is related to tracking for example, I can deny the connection right there and then.

**Comment by objective-see** [comment]
Great suggestion
...will be in the next version :) 

<img width="746" alt="Screen Shot 2021-02-05 at 4 25 42 PM" src="https://user-images.githubusercontent.com/11327812/107106381-72645000-67cf-11eb-9989-88da450b3621.png">

**Comment by objective-see** [comment]
now in released (v2.3) version!

**Comment by julienbordet** [comment]
Thanks ! That's perfect ;)

**Comment by dcaballero** [comment]
Awesome! I'll update this weekend.

Thanks!!

**Comment by KernelBypass** [comment]
> now in released (v2.3) version!

Can rules convert domain name to an IP using reverse DNS?

E.g., if an app resolves domain name to an ip via open port 53 and then tries to connect to an ip directly instead of using domain name, how do I make  LuLu grant the permission to connect to an ip if it's associated with a permitted domain? 

E.g., I have entire github whitelisted via the `^(.*\.)?github\.com$` regex, but an application still tries to connect to one of its numerous IPs.

**Comment by martin-braun** [comment]
@objective-see I have the same issue as @KernelBypass. An app requests a bunch of IPs directly, I wish to block those requests based on reverse dns value to prevent changing IPs from re-triggering.
