### ISSUE TITLE
Removing temporarily allowed PID when they stop existing.

### ISSUE THREAD

**Issue by Noirdemort** [objective-see/LuLu#322]
When clicking allow temporarily, LuLu adds that temp pid and permission under that app icon. But once process ends, it doesn't refresh cache of PID that are not there or don't belong to that process any more. 

This creates a huge list and confusion when searching through list.

<img width="1109" alt="Screenshot 2021-02-11 at 18 15 29" src="https://user-images.githubusercontent.com/45682557/107638088-20bb3a00-6c95-11eb-863a-435c50592b60.png">

None of these process exist and my computer restarted a couple of times since they were created. Yet they are still there obstructing speed and view scope.

**Comment by objective-see** [comment]
Thanks for the bug report!
...was able to repo, track down, and (just) committed a fix. 

Will be in the next (shortly) released version.

**Comment by objective-see** [comment]
fixed in: https://github.com/objective-see/LuLu/releases/tag/v2.3.1
