### ISSUE TITLE
Allowing to filter by PID or permission

### ISSUE THREAD

**Issue by Noirdemort** [objective-see/LuLu#323]
Would really be helpful if it was possible to search by using permission ("allow", "block") or by PID. Would really speed up the case when by accident some software is allowed or blocked permanent, or just want to check which ones are blocked.

<img width="1111" alt="Screenshot 2021-02-11 at 18 19 49" src="https://user-images.githubusercontent.com/45682557/107638541-bbb41400-6c95-11eb-9e53-30785c1cae2e.png">

Right now, it returns empty which leads to then going through the gigantic list and checking.

**Comment by objective-see** [comment]
Good suggestion, just committed code to add this
...will be in next release! 

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/11327812/107817114-c7491e80-6d19-11eb-961f-9d3feec4ad32.png">

**Comment by objective-see** [comment]
Added in: https://github.com/objective-see/LuLu/releases/tag/v2.3.1
