### ISSUE TITLE
Deny / Allow buttons not clickable

### ISSUE THREAD

**Issue by pasevin** [objective-see/LuLu#326]
Version: 2.3.0

Sometimes the text overflows, covering "Deny" and "Allow" buttons and there's no way to click on those buttons.

<img width="1010" alt="Screen Shot 2021-02-15 at 10 25 49" src="https://user-images.githubusercontent.com/1058469/107918457-bfd48000-6f7a-11eb-81bc-dbd4a95063d6.png">

**Comment by objective-see** [comment]
Thanks for the bug report! 
Fixed in: https://github.com/objective-see/LuLu/releases/tag/v2.3.1
