### ISSUE TITLE
Installation warning:  dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu

### ISSUE THREAD

**Issue by KelseyDH** [objective-see/LuLu#33]
This warning happens to me both when installing by brew:

```
17:52:12 ➜  LuLu_0.9.2  brew cask install lulu
==> Satisfying dependencies
==> Downloading https://github.com/objective-see/LuLu/releases/download/0.9.2/Lu
######################################################################## 100.0%
==> Verifying checksum for Cask lulu
==> Installing Cask lulu
==> Running installer script 'configure.sh'
==> installing
==> kext installed and loaded
==> launch daemon installed and loaded
==> dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu
==> dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu
==> dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu
==> install complete
🍺  lulu was successfully installed!
```

or by shell:

```
17:46:09 ➜  LuLu_0.9.2  sudo bash configure.sh -install
installing
kext installed and loaded
launch daemon installed and loaded
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu.app/Contents/MacOS/LuLu being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu.app/Contents/MacOS/LuLu being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/LuLu.app/Contents/MacOS/LuLu being ignored in restricted program because of @executable_path
```

Any advice on what it means?  I don't see the LuLu icon at the top of my menu bar, though I can find the LuluDaemon running in Activity Monitor.  Do I need to log out and log back in to trigger it, or has something gone wrong with my install?

**System details:**

MacBook Pro (Retina, 15-inch, Mid 2014)
MacOS Sierra 10.12.6 (16G1114)

**Comment by objective-see** [comment]
This was occurring as LuLu was marked as 'restricted' to prevent various code injection attacks, which had the side-effect of the Apple loader (dyld) generating such warnings about some of the legitimate, but dynamically linked frameworks that LuLu used.

LuLu now manually loads those frameworks, meaning the warning should go away!

Also, recent versions of LuLu improved the cmdline install process - so the install issues should now be fixed!
