### ISSUE TITLE
Why doesn't macOS show the Lulu Extension?

### ISSUE THREAD

**Issue by UnixCro** [objective-see/LuLu#331]
` kextstat |grep -v com.apple`

`'/Applications/LuLu.app/Contents/Library/SystemExtensions/com.objective-see.lulu.extension.systemextension'`

Just for information: You harm yourself if you work with a scareware like Cleanmymac

**Comment by objective-see** [comment]
LuLu uses a network (system) extension ...which is not a kext.

Use the `systemextensionsctl` command , with the `list` option

```
% systemextensionsctl list
1 extension(s)

--- com.apple.system_extension.network_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	VBG97UB4TA	com.objective-see.lulu.extension (2.3.0/2.3.0)	Extension	[activated enabled]
```
