### ISSUE TITLE
The destination IP address is always the router IP, not the remote IP.

### ISSUE THREAD

**Issue by mbseidel** [objective-see/LuLu#332]
If LuLu detects an outgoing connection, only the IP address of the own router is displayed, but not the external server IP or the URL. LuLu then shows "<Application> is trying to connect 192.168.xxx.xxx". Also at the bottom of the dialog windows there is only sayed "ip address: 192.168.xxx.xxx".

**Comment by bjorkollur** [comment]
I am having the same problem.

**Comment by objective-see** [comment]
This is "correct" in the sense that this is what macOS report to LuLu as it is the initial connection that is generated when an app wants to communicate with an external server (it is usually (always?) related to DNS - note port 53). 

If you allow this initial connection, but scope it to the "Remote Endpoint" the next request will be to the URL / IP that was DNS resolved. 

You can always add a global rule either to allow any/all connections to your router, or DNS requires:
![image](https://user-images.githubusercontent.com/11327812/110193709-a4220400-7dd9-11eb-817a-0b7ffb0cfad8.png)

...which will allow this initial connection.
