### ISSUE TITLE
Forgot files in your 2.3.0 DMG image root (either not hidden or left over)

### ISSUE THREAD

**Issue by mackonsti** [objective-see/LuLu#335]
Hello and thank you for your continuing support and development of LuLu!
Just to report that your DMG file contains in the root some files probably not removed/forgotten:

```
-rw-r--r--  1   67120 Dec  8 02:58 LuLu.icns
-rw-r--r--  1   13743 Feb  8 07:57 background.png
-rw-r--r--@ 1  163664 Feb  8 07:57 background.psd
-rwxr-xr-x@ 1     288 Feb  8 07:46 createDMG.sh
```

Not sure if this qualifies for a re-package of the DMG just to inform you, in case you missed it.
Thank you again.

**EDIT:** The background.png file exists in the hidden folder as expected, so this one above is certainly a left-over...

**Comment by objective-see** [comment]
ah thanks! 
fixed in https://github.com/objective-see/LuLu/releases/tag/v2.3.1
