### ISSUE TITLE
unnable to disable

### ISSUE THREAD

**Issue by Delostik** [objective-see/LuLu#36]
cannot disable lulu and close lulu...
latest macos

**Comment by alvarnell** [comment]
As far as I know the only way to do that is to uninstall LuLu. Did you try that?

**Comment by Delostik** [comment]
Oh I found the reason...
While the preference panel in on the desktop, I click "disable", it wouldn't work.
But if I close the panel, it works...

**Comment by objective-see** [comment]
This should be fixed now in recent versions of LuLu
...just tested the latest version and confirmed that one can disable LuLu, even if preference panel is open!

Please let me know if you are still seeing this issue though.
