### ISSUE TITLE
Lulu causes Postbox mail client to crash at startup

### ISSUE THREAD

**Issue by bmscmoreira** [objective-see/LuLu#369]
When using Lulu firewall for macOS, Postbox mail client will not start and crash immeadiately. If I disable Lulu, it will open again. I am using the latest versions: Postbox (7.0.48) and Lulu (2.3.1).

**Comment by bmscmoreira** [comment]
Sidenote: reported this as well to Postbox support.

**Comment by axeloz** [comment]
Same issue here with Postbox latest and Lulu latest. I tried to add a "Allow" rule to Postbox in Lulu but same.

**Comment by axeloz** [comment]
Sorry, just noticed @objective-see's reply : https://github.com/objective-see/LuLu/issues/285#issuecomment-749239710

**Comment by bmscmoreira** [comment]
Sorry too, didn't see the issue was already posted in #285. I will close this issue to avoid duplication.
