### ISSUE TITLE
Allow iOS simulator to pass through the Firewall (a.k.a. wildcard rules)

### ISSUE THREAD

**Issue by urosk** [objective-see/LuLu#379]
Whenever iOS simulator is launched from XCode, a new popup from LuLu needs to be approved.

The reason for this is that each time you build an app from XCode, and run it on a simulator, a new folder with an UDID string is created. This changes the path of the program.

This has been a pain in the ass for years now.  I end up just disabling the firewall.

The unwanted popups could be solved by allowing wildcard rules. The simplest solutions that come to mind:
- specify a folder as rule path to allow all programs within to access network
- specify just the app name as rule path, to allow all apps with this name to access network, regardless of their location on disk.

To check how Little Snitch handles this, read https://blog.obdev.at/ios-simulator-and-little-snitch-3-5/

**Comment by BlueCobold** [comment]
Before v2.0.0 Lulu did handle this with an option called "allowGlobally". It was removed in 2.0.0, though I'm not sure why.

**Comment by thesergeydavydov** [comment]
Yes yes, I tap allow around hundred time a day))

**Comment by housecode** [comment]
As far as i know when we start debugging XCode create new PID and that's why popups always comes out

**Comment by BlueCobold** [comment]
The problem is not a different PID, but the Simulator is moved o a different directory. So the path of the executable changes and that's why Lulu is asking again to block/whitelist the application and why we need a wildcard like in older versions.

**Comment by rizkhan7** [comment]
Please add this feature as it is really needed, thanks! :)

**Comment by objective-see** [comment]
LuLu v2.4.0 now (finally) supports this:

![Screen Shot 2021-10-16 at 9 16 39 AM](https://user-images.githubusercontent.com/11327812/137599783-5425559f-3504-44f6-b872-9f53d3754160.png)


...note that also, via the 'Add Rule' button (bottom right of the Rules window), you could now create a "Directory" rule that will apply to any item within that directory or any of its subdirectories:

![Screen Shot 2021-10-16 at 9 17 58 AM](https://user-images.githubusercontent.com/11327812/137599826-5ecee2be-8eb7-484a-944f-b7d3d7a77a84.png)
