### ISSUE TITLE
After upgrading to macOS 11.4 Lulu blocks VPN

### ISSUE THREAD

**Issue by scheinercc** [objective-see/LuLu#380]
Any idea if I can debug what might be the cause? I disabled Lulu for the time being.

**Comment by objective-see** [comment]
This was likely a bug in macOS. Apple just released macOS 11.5, with a handful of fixes. 

Can you upgrade and see if that addresses this issue? Thanks!

**Comment by scheinercc** [comment]
Will do and let you know!

**Comment by scheinercc** [comment]
And it works again. Thanks for letting me know!
