### ISSUE TITLE
Regain old OS support

### ISSUE THREAD

**Issue by ghost** [objective-see/LuLu#396]
Would it be possible to get updates for old OS again? Last version that seems to work is 1.2.3 but looking at the github it looks like there are a lot of new updates after that.

**Comment by objective-see** [comment]
Unfortunately Apple's Network Extension Framework, that LuLu leverages is only available on more recent versions of macOS (10.15+). A lot of LuLu's new features are only possible by leverage this framework. As such, it's not really feasible to add those to the older versions of LuLu. Sorry :(
