### ISSUE TITLE
LuLu causing Kernel panics 

### ISSUE THREAD

**Issue by seathasky** [objective-see/LuLu#399]
Def caused by LuLu, I bolded the causing factor below. Any help on this? Currently on Mac Catalina.

panic(cpu 3 caller 0xffffff80150c0fef): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.35/bsd/net/content_filter.c, line: 1067

Backtrace (CPU 3), Frame : Return Address

0xffffff83c4fdb8a0 : 0xffffff801491c63d

0xffffff83c4fdb8f0 : 0xffffff8014a56b25

0xffffff83c4fdb930 : 0xffffff8014a486ae

0xffffff83c4fdb980 : 0xffffff80148c2a40

0xffffff83c4fdb9a0 : 0xffffff801491bd07

0xffffff83c4fdbaa0 : 0xffffff801491c0f7

0xffffff83c4fdbaf0 : 0xffffff80150c0b5c

0xffffff83c4fdbb60 : 0xffffff80150c0fef

0xffffff83c4fdbb70 : 0xffffff8014cd7f3e

0xffffff83c4fdbbb0 : 0xffffff8014cd7c27

0xffffff83c4fdbbd0 : 0xffffff8014cd6c22

0xffffff83c4fdbc20 : 0xffffff8014cd356e

0xffffff83c4fdbc80 : 0xffffff8014e5a5c9

0xffffff83c4fdbcd0 : 0xffffff8014ed236b

0xffffff83c4fdbdf0 : 0xffffff8014ea6f2c

0xffffff83c4fdbe20 : 0xffffff8014ea0520

0xffffff83c4fdbee0 : 0xffffff8014ea02e0

0xffffff83c4fdbf40 : 0xffffff8014f83cd7

0xffffff83c4fdbfa0 : 0xffffff80148c3206

**BSD process name corresponding to current thread: com.objective-se**.     **<-----------------  LOOK HERE**

Boot args: -keepsyms=1 -debug=0x100 -alc=1

Mac OS version:

19H1323

Kernel version:

Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64

Kernel UUID: EA37759C-12E3-3509-AD57-4B4A4FC5E7AD

Kernel slide: 0x0000000014600000

Kernel text base: 0xffffff8014800000

__HIB text base: 0xffffff8014700000

System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)

System shutdown begun: NO

Panic diags file available: YES (0x0)

System uptime in nanoseconds: 150497355444328

**Comment by objective-see** [comment]
This is a known *Apple* bug.
The (only) solution is to upgrade to the latest version of macOS (macOS Big Sur/11), as this is where Apple's fixed the issue :/

**Comment by seathasky** [comment]
Not a big deal, it  doesn't happen all the time and most of the applications I use have auto-save but it does happen at least once a day. Someone in another post was saying it was related to having Google Chrome open so I uninstalled that 👍

**Comment by elesto** [comment]
I wont ever be "upgrading" to catalina since my mac is too old now. Will we ever get any love on the old 1.2.3 version?

**Comment by seathasky** [comment]
> I wont ever be "upgrading" from catalina since my mac is too old now. Will we ever get any love on the old 1.2.3 version?
How old is your Mac? I currently have Catalina installed on a very old Macbook Air 2010. 
You can see if yours is supported here: http://dosdude1.com/catalina/

**Comment by elesto** [comment]
Sorry I wasnt clear, I meant I cant update from catalina to Big sur. Do you know of any patches to apply to catalina that fixes the panics?

**Comment by seathasky** [comment]
same thing: https://bensova.gitbook.io/big-sur/ different patch

**Comment by elesto** [comment]
Thanks
