### ISSUE TITLE
BigSur + Facetime + iPhone Calls

### ISSUE THREAD

**Issue by lehrig** [objective-see/LuLu#401]
On BigSur (11.4), LuLu (2.3.1) appears to cause problems when integrating Facetime with iPhone Calls. I can neither start mobile phone calls nor receive phone calls via my Mac when Lulu is enabled, even though all Apple rules are "allowed". I am not asked for any additional rules to setup.

Can anybody confirm this behaviour?

**Comment by objective-see** [comment]
Prior to macOS 11.5, there were a myriad of bug's in Apple's Network Extension Framework (that LuLu leverages). Such bugs would impact products, such as LuLu, in the manner you described. 

The good news is the solution is simply to update to macOS 11.5+ (as this contains Apple's fixes).

**Comment by lehrig** [comment]
Confirmed, after upgrading to macOS 11.6, everything works as expected. Thanks!
