### ISSUE TITLE
Lulu doesn't automatically launch, even when added to Login Items

### ISSUE THREAD

**Issue by huzzam** [objective-see/LuLu#409]
Lulu is working fine here, except that I can't get it to start automatically. On system boot, Activity Monitor confirms that no app named Lulu is running. I've tried adding Lulu to the Login Items, and it still doesn't start. 

i'm on the latest Big Sur, macOS 11.6

edit: i'd installed Lulu via Homebrew. I removed it from Homebrew and installed it directly from here, and now it's launching correctly! Had the same issue with Rectangle, so it seems perhaps there's something sideways about Homebrew & auto-launching apps.

**Comment by ipatch** [comment]
so when you removed the homebrew installation of lulu, how did you backup all of your rules, so you didn't have to recreate them?

**Comment by huzzam** [comment]
I didn't, I started again from scratch.

**Comment by ipatch** [comment]
could be useful if you end up back here.

https://github.com/objective-see/LuLu/issues/406#issuecomment-961575108
