### ISSUE TITLE
macOS 12.2 - wifi intermittent connection failure

### ISSUE THREAD

**Issue by scheinercc** [objective-see/LuLu#438]
Upgraded to macOS 12.2 two days ago and today the wifi suddenly stopped working. It worked after a restart, but stopped again a few minutes later. Tested with `ping 1.1.1.1`. Worked while Lulu disabled, stopped when enabled. I don't recall a change of rules since the upgrade.

Re-enabling Lulu several minutes later, `ping 1.1.1.1` works, though.

This is on an Apple M1 Pro.

**Comment by Somberland** [comment]
Had to reboot 4-5times a day otherwise some connections got stuck etc. removed for now. is there a way to help with debug-information etc?

**Comment by boyerst** [comment]
Same issue, fixed after a few restarts and reintroduced after ~2 days. Tried reinstallation, network reset with no success.

macOS 12.0.1, Intel

**Comment by tenderloin** [comment]
Same issue - I finally had to disable LuLu - made connections too unreliable.

**Comment by scheinercc** [comment]
On macOS 12.2.1 now and Lulu 2.4.1. Haven't had the issue again. @Somberland & @boyerst do you have Lulu turned on? Does it work for you now?
@tenderloin what version of OS and Lulu are you running?

**Comment by tenderloin** [comment]
I had turned it off on MacOS 12.2 and Lulu 2.4.1. I can try again today.

**Comment by boyerst** [comment]
@scheinercc All updated and back to blocking! (macOS 12.2.1, Lulu 2.4.1)

**Comment by scheinercc** [comment]
Hmm, ok. If I find out if there was something I changed I'll let post it here, otherwise might have to wait for Patrick to take a look.

**Comment by scheinercc** [comment]
Thanks for clarifying! Will go ahead close this ticket.
