### ISSUE TITLE
Deleting application without running uninstall -> networking issues

### ISSUE THREAD

**Issue by jonathankau** [objective-see/LuLu#44]
In case anyone else runs into this, simply removing the installed application isn't enough. I was running into strange problems in which I could access websites via my browser, but `curl` wasn't working in my Terminal. Running the uninstall script fixed these problems.

**Comment by alvarnell** [comment]
Appreciate your confirming that the uninstall script works, but wonder why you felt it necessary to file as an "Issue".

I think you learned a valuable lesson, though. Never assume that you can uninstall any 3rd party software by simply trashing the application without consulting the developer on the proper method that should be used. Even users of helper apps like AppDelete aren't guaranteed of being able to get rid of all running processes these days.

**Comment by jonathankau** [comment]
Sorry about that! Didn't necessarily mean to file this as an issue, but wanted to put this out there in case anyone else runs into the same problem in the future.

I had actually disabled LuLu for a couple of months, so by the time I was going through and cleaning up Applications, it didn't occur to me that LuLu would still have running processes/network settings that needed to be reconfigured. Definitely a good lesson though!
