### ISSUE TITLE
Bir Sur non-notarised script

### ISSUE THREAD

**Issue by iBeloved** [objective-see/LuLu#447]
Have a issue with a bash script running via a LauncgDaemons .plist
The .plist is set to refresh ever 2 minutes and as such theres a LuLu (2.4.1) notification that pops up.
Yes, I can Allow and the script seems to run ok.
The script in question is Peter Mollers "open_ports.sh" which refreshes via the plist.
I've searched for references and so far little bits and pieces that don't fit the LuLu process.
Any idea anyone?

**Comment by iBeloved** [comment]
[](url
![Screenshot 2022-03-13 at 11 44 38](https://user-images.githubusercontent.com/28103538/158057848-e32dfd97-3e6c-4cd3-b945-d447989cc8bb.png)
)

**Comment by Jymit** [comment]
@iBeloved Whats the issue here? To me this looks like working as expected.
The script is not notarized so this being flagged is a _good_ thing. Flagging this is an extra win. 

Happy to help and share more understanding on notarization where needed :)

**Comment by objective-see** [comment]
This is actually a BlockBlock alert (https://objective-see.org/products/blockblock.html) ...not LuLu

For BlockBlock if you have turned on "Notarization Mode" it will block non-notarized scripts:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/11327812/176159483-713e348a-a834-4313-995e-6451d32f185d.png">

You can either:
1. Disable that preference in BlockBlock 
2. For this script (`open_ports.sh`) remove the quarantine attribute in a terminal, via `xattr -rc /usr/local/bin/open_ports.sh`
