### ISSUE TITLE
Incorrect version displayed in preferences window

### ISSUE THREAD

**Issue by nicolas-lesage** [objective-see/LuLu#45]
Hello,
Minor issue, I've just installed LuLu 0.9.2, but in the preferences window 0.9.1 is still displayed (cf screenshot attached).
Otherwise I like the idea a lot, keep up the good work!

<img width="620" alt="lulu" src="https://user-images.githubusercontent.com/16035349/36970484-0e318a22-2069-11e8-9848-6dd003f4a676.png">

**Comment by objective-see** [comment]
Fixed! Thanks :)
