### ISSUE TITLE
Is there a data privacy note? 

### ISSUE THREAD

**Issue by Ein-Tim** [objective-see/LuLu#454]
Hey, thanks for this great project! I'd like to use this app and already tried it myself, but I'm wondering if there is a data privacy note or some sort of information which data LuLu collects and sends to its servers (there must be at least one central server as there is an in-app-update checker).

Thanks for your response!

**Comment by Shade717** [comment]
Hello! I'm also very interested in this question. Does the program send any data to the server?
Thanks

**Comment by Shade717** [comment]
Is there any information?

**Comment by Ein-Tim** [comment]
I stopped using this program and I'm thus withdrawing this question.
