### ISSUE TITLE
Will Netiquette be updated?

### ISSUE THREAD

**Issue by hisel-sabermetrics** [objective-see/LuLu#458]
Current Lulu version include Netiquette version 1.2.0.

Will it be updated to version 2.0.0?

**Comment by rob-zukaz** [comment]
Same issue, is there any way to have LuLu check if a standalone Netiquette app already exists, then use that app version instead of the in-built one?

**Comment by objective-see** [comment]
Just released LuLu v2.4.2 with the latest version of Netiquette packaged in it: https://github.com/objective-see/LuLu/releases/tag/v2.4.2

...yes, might be a better way to always ensure the latest version of Netiquette is used. Will think on that!
