### ISSUE TITLE
Autostarting LuLu seems broken

### ISSUE THREAD

**Issue by artemislena** [objective-see/LuLu#463]
L: LuLu doesn't automatically start on system login. We tried a lot of things, like reinstalling LuLu, or removing and then readding it in Users & Groups > Login Items in System Preferences, but it always needs to be started manually. Note that other login items (such as BlockBlock or ReiKey) do work, so this seems like a LuLu-specific issue, not an issue with our system, which, for the record, is a MacBook Air M1. Manually starting works, but it's easily forgotten, meaning LuLu doesn't provide the protection it should provide.

**Comment by artemislena** [comment]
Oh. https://github.com/objective-see/LuLu/issues/409 We searched for similar issues, but didn't find that one at first. So yeah, seems autostarting LuLu if it's installed from HomeBrew doesn't work.

**Comment by gcpmusic** [comment]
No, I installed Lulu and all following updates via HomeBrew both on Mojave and Monterey (Intel) and always worked as expected. No issue whatsoever here.

You did not mention your OS and Hardware, anyhow the issue must be at your end.
