### ISSUE TITLE
Disable an app from accessing a specific URL

### ISSUE THREAD

**Issue by justsharan** [objective-see/LuLu#473]
Hey, I'd like to disable an app from accessing a particular URL (not an entire domain, so I can't use `/etc/hosts` or any other hostname-based option), and I was wondering if there's an option for this with LuLu.

**Comment by fulldecent** [comment]
This is outside the scope of howe LuLu works. 

LuLu is a firewall for network connections. Inspecting a network connection does not provide information on what URL is contained inside as that is encrypted.

Recommend to close this issue and consider other software such as Charles Proxy or Wireshark.
