### ISSUE TITLE
LuLu 0.9.3 completely breaks WLAN access on MacOS 10.12.6

### ISSUE THREAD

**Issue by GraOrigin** [objective-see/LuLu#48]
Tried the latest beta, only to be presented with the following scenario;

Able to connect to my WLAN, although there's a "!" on it => no Internet connection (told by MacOS to restart router or call ISP) 
Router reboot did nothing of any sort, only way out is to disable LuLu..
I'm back on 0.9.2, which works - gladly

Thanks so much for all the time & work you spend on this and other things to enhance the Apple-Universe! 

All the best

**Comment by GraOrigin** [comment]
well, the workaround only works if one does not use a VPN, which probably correlates to #50 ...

**Comment by MiKatre** [comment]
Same here. So I uninstalled Lulu. Yet the wifi still has trouble connecting and vpn doesn't work anymore.

**Comment by emilkaae** [comment]
I am quite excited about Lulu, which could turn out to be another valuable tool for hardening the Mac.
I am facing similar problems with WiFi and VPN connections failing as long as Lulu v0.9.3 is enabled.
OSX version 10.13.3 (17D102).

**Comment by objective-see** [comment]
opps sorry! 
had a bug where certain UDP response packets would be blocked, when all should be allowed. 

commit https://github.com/objective-see/LuLu/commit/e86968c7472b93cd72d97fea72de23a2d07e386c#diff-ca6bed8b166f029e3f85be3c7ce2e918 fixes this

**Comment by objective-see** [comment]
opps sorry! thanks for reporting :)
tracked this down to a a bug which caused certain UDP response packets to be blocked, when all should be allowed. 

commit https://github.com/objective-see/LuLu/commit/e86968c7472b93cd72d97fea72de23a2d07e386c#diff-ca6bed8b166f029e3f85be3c7ce2e918 fixes this 

(note: will be releasing v0.9.4 next week that will include this fix in the build)

**Comment by hohler** [comment]
I have the same problem on macOS 12.1 Monterey on a M1 Pro. only disabling LuLu gives me access to the internet over WiFi.

**Comment by iAmXquisite** [comment]
This problem is still ongoing. I just restarted my MacBook M1 Pro and after restarting, I had to disable Lulu for my internet to work. After 10 minutes, I re-enabled Lulu and the internet is working again. I think it takes some time for it to realize that it doesn't have to block the internet.

**Comment by ashj403** [comment]
Consistently running into this issue still, this forced me to uninstall LuLu as its not worth having the constant connectivity issues
