### ISSUE TITLE
(nearly) Infinite notifications are possible, issue temporarily resolved by killing helper application

### ISSUE THREAD

**Issue by CoffeePocket** [objective-see/LuLu#49]
Related issues: 
https://github.com/objective-see/LuLu/issues/46
https://github.com/objective-see/LuLu/issues/20

Under certain circumstances, LuLu can get caught in an apparently infinite popup notification loop.

In my case, this happened when I left the notification popup open while searching for information about what nsurlsessiond was connecting to, and then went for dinner.

It appeared that nsurlsessiond kept trying to connect in the meantime, creating more notification queue entries while I was away.

Then once I clicked "accept", LuLu proceeded to show me identical popup warnings for as long as I cared to keep clicking "accept."

Killing the LuLu Helper application fixed the problem -- it restarted, showing just ONE popup asking about nsurlsessiond, and everything went on its merry way.

It looks like LuLu needs some internal notification dupe checking.

**Comment by jaulz** [comment]
Same issue here 👎

**Comment by objective-see** [comment]
Should be fixed in v. 0.9.4. 
If the issue still persists, please let me know :)
