### ISSUE TITLE
Lulu `com.objective-see.lulu.extension` taking all available CPU & RAM and persistently relaunching (to then repeat this activity).

### ISSUE THREAD

**Issue by sjclark** [objective-see/LuLu#490]
Absolutely love Lulu, and have found it super bullet-proof - which is why it's super odd that I'm suddenly having Lulu utilise all CPU & Ram, and keep re-launching itself event after force-quitting both the application and extension.

Can you please let me know what logs or information I can provide?

This locked my computer up so much even Activity Monitor wouldn't run - had to restart (note it using 40GB of Ram - primarily Swap)
<img width="1149" alt="Screen Shot 2022-09-28 at 12 24 22 pm" src="https://user-images.githubusercontent.com/4531017/192674662-2c376f88-abf5-4954-b09b-a649395d6b2e.png">

Upon re-launch it just repeatedly utilises any and all cpu and ram...
<img width="306" alt="Screen Shot 2022-09-28 at 12 29 58 pm" src="https://user-images.githubusercontent.com/4531017/192674670-b3c6c422-9b2c-4a60-8b32-4f4711832df6.png">

It also makes the entire network unresponsive (even uploading these screenshots and posting this issue was a battle against the extension repeatedly re-launching itself.
<img width="571" alt="Screen Shot 2022-09-28 at 12 30 25 pm" src="https://user-images.githubusercontent.com/4531017/192674680-82166413-1f13-4935-94a9-a383497df8ac.png">

<img width="853" alt="Screen Shot 2022-09-28 at 12 30 36 pm" src="https://user-images.githubusercontent.com/4531017/192674690-26e7fcf6-2439-4f7e-92ea-2d8ec630dab3.png">

No idea what to do.

On a MacBook Pro (15-inch, 2017) macOS Big Sur 11.7

<img width="607" alt="Screen Shot 2022-09-28 at 12 39 00 pm" src="https://user-images.githubusercontent.com/4531017/192675133-301b9bfd-ee77-4104-a439-119a53482507.png">

**Comment by zzronggg** [comment]
Same here. It happened in today's morning but everything was fine before this.

**Comment by zzronggg** [comment]
@sjclark Try to quit lulu from the menu bar and regrant the privilege. I solved it.

**Comment by sjclark** [comment]
Tried reg-ranting privileges, reinstalling, restarting etc.

Gave Up - ohwells 🤷‍♂️ 

<img width="440" alt="Screen Shot 2022-09-30 at 3 35 19 pm" src="https://user-images.githubusercontent.com/4531017/193197657-52d25308-6bf0-4331-b1bd-2ca156bb5edc.png">

**Comment by af1** [comment]
> @sjclark Try to quit lulu from the menu bar and regrant the privilege. I just solved it in this way.

Worked for me. Thanks.

**Comment by Skytale23** [comment]
> > @sjclark Try to quit lulu from the menu bar and regrant the privilege. I just solved it in this way.
> 
> I quit, reopened, and was re-prompted to grant Lulu permission in the Security & Privacy panel.
> 
> Worked for me. Thanks.

Ditto, worked here too - M1 - OS 12.6

**Comment by sjclark** [comment]
> > Worked for me. Thanks.
> 
> Ditto, worked here too - M1 - OS 12.6

It worked for me initially - then the issue just came back later.

**Comment by zzronggg** [comment]
>
quit it and restart 1 to 2 times, then reopen it

**Comment by OlivierL-KRG** [comment]
Same here.
Intel 16 inch MBP.
Lulu 2.4.2

**Comment by OlivierL-KRG** [comment]
I solved it by killing the Lulu pid processes:
`❯ ps aux | grep -i lulu
root               310  96.9 27.5 130025616 18479228   ??  Rs    6:38PM  14:07.87 /Library/SystemExtensions/72B9216A-20C5-43B5-9CAA-FE311E192F7E/com.objective-see.lulu.extension.systemextension/Contents/MacOS/com.objective-see.lulu.extension
olivier            710   0.0  0.0 36408232  31736   ??  S     6:39PM   0:00.46 /Applications/LuLu.app/Contents/MacOS/LuLu

❯ sudo kill -9 310 710
`

Then I uninstalled the system extension (I had to disable SIP temporaly):
`systemextensionsctl uninstall VBG97UB4TA com.objective-see.lulu.extension`

Then I restarted Lulu.app.
Everything is now fine, and I kept all my rules.
