### ISSUE TITLE
Lulu displays IP in 4 digit format

### ISSUE THREAD

**Issue by Tomasv-20** [objective-see/LuLu#504]
Did not found a root cause, M1 processor, but seen in on my older Intel based Mac as well.

I expect IPv4 there

<img width="311" alt="image" src="https://user-images.githubusercontent.com/119470825/204700646-730cb2de-1302-4256-adf4-9ad2f8714f21.png">

**Comment by Tomasv-20** [comment]
Anyone any comments or ideas on how to fix, please?

**Comment by hisel-sabermetrics** [comment]
It's probably because the process is using IPv6.

**Comment by Tomasv-20** [comment]
@hisel-sabermetrics OK, how do I change the binding or settings? Is that even possible? THX!

**Comment by hisel-sabermetrics** [comment]
Just set your DNS to one that uses IPv4

**Comment by objective-see** [comment]
Yes, this is the IP address given to LuLu by macOS (See [this line of code](https://github.com/objective-see/LuLu/blob/7d8bf183396d01df669f2f37b5eac1f86047dbdf/LuLu/Extension/Alerts.m#L95). 

...LuLu doesn't change/format this. 

If its an IPv6 address, it will be in that 4-digit format (again, as delivered to LuLu by the system).
