### ISSUE TITLE
a question about logging

### ISSUE THREAD

**Issue by engineer-plus-plus** [objective-see/LuLu#514]
Does Lulu keep the logs of processed requests?  Which ones were rejected, etc?  Where would one find such logs?  Many thanks.

**Comment by objective-see** [comment]
LuLu uses the system ("unified") log to messages.
For example see [this line of code](https://github.com/objective-see/LuLu/blob/7d8bf183396d01df669f2f37b5eac1f86047dbdf/LuLu/Extension/FilterDataProvider.m#L606).

To see its output, hop into the terminal and run
```log show --debug --info  --predicate="subsystem='com.objective-see.lulu'"```

(Or via Console.app). 

How long these log messages are stored is up to macOS/the unified log settings.
