### ISSUE TITLE
Why does Lulu connect to googleusercontent.com ?

### ISSUE THREAD

**Issue by andylundqvist** [objective-see/LuLu#531]
I am using Lulu 2.4.2 and Netiquette 2.1.1.

<img width="1435" alt="219903627-e475ebc3-55ba-4d0c-87cc-2163d995e9ed" src="https://user-images.githubusercontent.com/55158699/229900033-374f50a0-e973-452a-9b60-fe6ebf62b444.png">

Why does Lulu and Netiquette connect to googleusercontent.com?

I can not find any Data Privacy document on the Objective See website (or, as far as I can see, inside the different softwares) and this connection to googleusercontent.com (owned by markmonitor.com / Newfold Digital Inc.) can not be GDPR compliant and is generally very dodgy and not suiting for software supposed to protect its users.

I also created [an issue for Netiquette](https://github.com/objective-see/Netiquette/issues/10) but so far nobody has responded.

**Comment by objective-see** [comment]
LuLu (and Netiquette) use sentry.io (https://sentry.io/) for error reporting. 

As the screenshot of the LuLu alert shows, the googleusercontent.com URL the/a reverse DNS lookup of the `sentry.io` domain:
![Screenshot 2023-04-04 at 10 29 40](https://user-images.githubusercontent.com/11327812/229913137-4eca89f8-04c0-4df5-b20d-c4b6c791e8d8.png)

This error reporting data, according to Sentry is GDPR compliant. 
See ["Are you compliant with General Data Protection Regulation (GDPR)?"](https://help.sentry.io/account/legal/are-you-compliant-with-general-data-protection-regulation-gdpr/)

Regardless, we're working on a version with a preference to disable error reporting all together 😇

**Comment by andylundqvist** [comment]
Thanks for the explanation and thanks for making it possible to disable crash reporting.
