### ISSUE TITLE
(maybe not for here) Photoshop 2023 crash on Ventura with LuLu

### ISSUE THREAD

**Issue by poudenes** [objective-see/LuLu#538]
Hi all,

I did a clean install of Ventura and installed my Photoshop. It was crashing all the time.
When I removed Lulu and installed little snitch Photoshop work like a beast.

I don't know if this issue belong here or not. Because with Little Snitch there is no issue.

Greets,

**Comment by mdjunior** [comment]
Could you provide more details about your Lulu installation and logs in the scenario you were using?

I believe that for other people to be able to help you could provide your configuration and the logs using the following commands:

Logs:
```
log stream --level debug --predicate="subsystem='com.objective-see.lulu'"
```

Preferences:
```
cat /Library/Objective-See/LuLu/preferences.plist
```

**Comment by poudenes** [comment]
I'm so sorry, but for me it was urgent to have photoshop working again. Lulu is uninstalled and I can't send any information you ask...

**Comment by PencilNotPen** [comment]
> Hi all,
> 
> 
> 
> I did a clean install of Ventura and installed my Photoshop. It was crashing all the time.
> 
> When I removed Lulu and installed little snitch Photoshop work like a beast.
> 
> 
> 
> I don't know if this issue belong here or not. Because with Little Snitch there is no issue.
> 
> 
> 
> Greets,
> 
> 

Which connections did you block for Photoshop with Little Snitch? All, or only some? Lulu also makes Photoshop crash for me, I want to try Little Snitch with your configuration. Thank you!

**Comment by poudenes** [comment]
I deny all connections of Photoshop.

**Comment by z0ng33** [comment]
I had the same problem, solved it like this. This rules will allow only DNS requests.

<img width="1015" alt="" src="https://github.com/objective-see/LuLu/assets/47711838/ee0d4e54-f1b9-4fad-b44f-bcd8eced1c8d">

**Comment by poudenes** [comment]
nice. Let me check this. If its working then I revert back to Lulu...

**Comment by Akhilesh-pandey1** [comment]
For those facing the crash issue within one minute, follow these steps:
First, allow 192.168.0 using a regex rule, and then block all other ports.
This should resolve the problem.
