### ISSUE TITLE
Cannot connect with builtin VPN on LULU 0.9.3 and OSX 10.13.4

### ISSUE THREAD

**Issue by emilkaae** [objective-see/LuLu#54]
With LULU enabled, I cannot connect through the built in Cisco IPSec VPN client. If I disable, I can connect to VPN and then re–enable LULU afterwards.

**Comment by sancao2** [comment]
so did I ...

**Comment by strogonoff** [comment]
Happening with Tunnelblick and ProtonVPN’s native client app on 10.12. Disabling temporarily helps.

**Comment by heywoodlh** [comment]
I was having similar issues. Just updated to the beta and that seems to have fixed my issues with Tunnelblick.

**Comment by objective-see** [comment]
Sorry for the issue!

The latest version (v.0.9.4) should fix this. Please let me know if you're continuing to see the 'broken' behavior!

**Comment by emilkaae** [comment]
v.0.9.4 seems to have fixed the VPN issue.
