### ISSUE TITLE
2.5.0 Your computer was restarted because of a problem

### ISSUE THREAD

**Issue by big610** [objective-see/LuLu#541]
2.5.0 Your computer was restarted because of a problem

panic(cpu 1 caller 0xffffff800cac084f): assertion failed: (MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start == cfq->q_end) || (!MBUFQ_EMPTY(&cfq->q_mq) && cfq->q_start != cfq->q_end), file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.66/bsd/net/content_filter.c, line: 1067
Backtrace (CPU 1), Frame : Return Address
0xffffff912c6a38a0 : 0xffffff800c31b54d 
0xffffff912c6a38f0 : 0xffffff800c455d85 
0xffffff912c6a3930 : 0xffffff800c44790e 
0xffffff912c6a3980 : 0xffffff800c2c1a40 
0xffffff912c6a39a0 : 0xffffff800c31ac17 
0xffffff912c6a3aa0 : 0xffffff800c31b007 
0xffffff912c6a3af0 : 0xffffff800cac03bc 
0xffffff912c6a3b60 : 0xffffff800cac084f 
0xffffff912c6a3b70 : 0xffffff800c6d7aee 
0xffffff912c6a3bb0 : 0xffffff800c6d77d7 
0xffffff912c6a3bd0 : 0xffffff800c6d67d2 
0xffffff912c6a3c20 : 0xffffff800c6d311e 
0xffffff912c6a3c80 : 0xffffff800c859d69 
0xffffff912c6a3cd0 : 0xffffff800c8d1b3b 
0xffffff912c6a3df0 : 0xffffff800c8a66fc 
0xffffff912c6a3e20 : 0xffffff800c89fcf0 
0xffffff912c6a3ee0 : 0xffffff800c89fab0 
0xffffff912c6a3f40 : 0xffffff800c983517 
0xffffff912c6a3fa0 : 0xffffff800c2c2206 

BSD process name corresponding to current thread: com.objective-se

Mac OS version:
19H2026

Aloha hoa noho kakahiaka pomaika'i

**Comment by objective-see** [comment]
This is a known Apple bug 🍎🐛
Yes, LuLu (which runs 100% in user mode) triggers it, but it's an issue in Apple's macOS' kernel code. 

The (only) solution is to upgrade to a version of macOS that is Big Sur (macOS 11) or newer ...as this is where Apple's fixed the issue.
