### ISSUE TITLE
why occasionally request sentry.io:443

### ISSUE THREAD

**Issue by AjianNie** [objective-see/LuLu#543]
I want to know why LuLu and Netiquette occasionally request sentry.io:443?

This website seems to be related to user information: Application Performance Monitoring & Error Tracking Software, but I did not find any relevant explanations or settings in LuLu.

In the picture below, 517B represents the data uploaded in a single instance.
![1](https://github.com/objective-see/LuLu/assets/108182750/8685b3a0-386f-4796-be3f-1f24c3320be5)
![2](https://github.com/objective-see/LuLu/assets/108182750/ccd6c2d2-0318-4104-949f-9643f2297227)

**Comment by etherx-dev** [comment]
devs are spying on you

**Comment by objective-see** [comment]
This was simply the (anonymized) open-source crash report service these tools used. 

All error reporting has been removed from both LuLu (https://github.com/objective-see/LuLu/releases/tag/v2.6.0) and Netiquette (https://github.com/objective-see/Netiquette/releases/tag/v2.2.0).
