### ISSUE TITLE
allow localhost by default or add option to create such rule

### ISSUE THREAD

**Issue by gondo** [objective-see/LuLu#55]
connecting to `127.0.0.1` should be allowed by default
or at least please add the option to create a rule that would allow such connection for ANY application.

**Comment by objective-see** [comment]
Mahalo!  
Version 0.9.6 allows connections to localhost by default

Can test with: `$ nc 127.0.0.1 123` or `nc -6 127.0.0.1`
...this should no longer generate an alert :)
