### ISSUE TITLE
Using VPN with Lulu breaks internet

### ISSUE THREAD

**Issue by Rickdiculousme** [objective-see/LuLu#554]
Thank you for creating Lulu! I don't know if it's an OVPN problem or a lulu problem, but I find that when using OVPN I need to disable lulu otherwise all of my internet connections will freeze as soon as the program starts. When I'm connected to the vpn I can re-enable lulu, but then I must disable lulu before i disconnect. When the internet connection freezes is freezes almost all of my apps and I can't quit things like word, outlook, firefox, etc. and lulu doesn't respond. Even a force quite of lulu doesn't work. The only way to get it going again is to restart the computer after a bunch of force quitting of all my open apps

**Comment by halafi** [comment]
no issues pia vpn + wireguard or openvpn protocol

**Comment by Rickdiculousme** [comment]
The issue is gone with the latest update 👍

**Comment by SandboChang** [comment]
See the same issue with a brief test of Lulu and Wireguard, not sure what was still wrong.
