### ISSUE TITLE
Why do you Spy?

### ISSUE THREAD

**Issue by etherx-dev** [objective-see/LuLu#555]
Just remove the sentry logging or make it more clear with a consent screen, this has gotta stop m8.

**Comment by cy4n** [comment]
does this help?
![image](https://github.com/objective-see/LuLu/assets/1135762/3707e3bc-490b-42ef-bff8-e0f5113d34d2)

**Comment by objective-see** [comment]
Worth noting that Netiquette (NQ) is a separate app/utility that is bundled with LuLu. 

I've also gone ahead and fully removed error reporting from the NQ project as well: https://github.com/objective-see/Netiquette/releases/tag/v2.2.0

The next version of LuLu will be packaged with this "no error reporting" version of NQ.

**Comment by objective-see** [comment]
Thank you for your feedback and patience.

All error reporting has been removed from LuLu (https://github.com/objective-see/LuLu/releases/tag/v2.6.0) and Netiquette (https://github.com/objective-see/Netiquette/releases/tag/v2.2.0).

Favor: As there now is no way to see if/when these tools crash, please manually submit any crashes you encounter, so they can be fixed for everybody 🙏🏽
