### ISSUE TITLE
Alert rules

### ISSUE THREAD

**Issue by memeplex** [objective-see/LuLu#559]
I have disabled Allow Apple programs. I kind of trust Apple but take for example ssh, it's like trusting on the manufacturer of the gun they are pointing at me. It leaks everywhere, a random app or extension may call home via ssh.

What I would like is to trust Apple by default but be alerted about certain apps nevertheless. I don't want to block ssh outgoing connections altogether, of course. At the moment the only solution I found is to be alerted of everything Apple.

Maybe a list could be added of apps that always trigger alerts. Or, more generally, an "Alert rule" (not block, not allow, but alert) could be added.

**Comment by mdjunior** [comment]
I understand you perfectly, but today there is already a list of binaries in LuLu that is Graylisted. You can check this list here: 
https://github.com/objective-see/LuLu/blob/ba066deee82d30ecaf7d09792a8a2947ded4ba7c/LuLu/Extension/GrayList.m#L16

There is a processing order for the rules that you might want to consult to find out when this list is checked. You can check it here: https://github.com/objective-see/LuLu/issues/540

**Comment by memeplex** [comment]
Interesting, thanks for the explanation! I'm going to close this and give that a try.
