### ISSUE TITLE
Block command line utilities by parent process

### ISSUE THREAD

**Issue by farmerchris** [objective-see/LuLu#57]
/usr/bin/curl is Apple-signed, and so allowed by default. Fine if I'm in Terminal and calling curl manually. But if some malicious program shells out to curl to push data to a rogue server, I might want to know about that. I request that if a command line tool is using the network, maybe LuLu could expose a notification combining curl with parent GUI process as a pair and let me choose to block or allow that.

**Comment by alvarnell** [comment]
I know in the case of Little Snitch, there is an alert against the running process any time it attempts to use curl with a new URL. I would think that LuLu should do same, but haven't tested.

**Comment by objective-see** [comment]
LuLu's current approach is now to `gray list` such binaries.

Thus `curl` (and other binaries such as `nc` etc) will now generate an alert. This alert can also be approved 'temporarily' so just that (trusted) instance of `curl` will be allowed:

![image](https://user-images.githubusercontent.com/11327812/43033503-0e6c7272-8cd4-11e8-8c60-05742c800cd7.png)


You'll still have to examine the process hierarchy, or see where `curl` is connecting to (both in the alert window) to determine if it's a 'safe' instance
