### ISSUE TITLE
MacOS can't get correct permissions on MacOS Sonoma 14.1.2  for Lulu

### ISSUE THREAD

**Issue by 4cecoder** [objective-see/LuLu#572]
### Weird error on Sonoma MacOS 14.1.2 (23B92)

<img width="284" alt="Screenshot 2023-12-14 at 5 12 30 PM" src="https://github.com/objective-see/LuLu/assets/88108711/36294cb1-6043-4597-bb11-70b1749c208f">

### Doesn't show up on the list of security extensions in order to enable networking permissions for this "Extension" 

<img width="466" alt="Screenshot 2023-12-14 at 5 16 25 PM" src="https://github.com/objective-see/LuLu/assets/88108711/4725a66c-c5f3-4771-ad77-1a2778ace39f">

<img width="485" alt="Screenshot 2023-12-14 at 5 16 38 PM" src="https://github.com/objective-see/LuLu/assets/88108711/1e9d35ab-0bfd-425b-aa5e-6dab8382b856">

**Comment by daron4ever** [comment]
<img width="484" alt="Screenshot 2023-12-16 at 01 10 44" src="https://github.com/objective-see/LuLu/assets/18229512/2e06c987-7baa-436c-aa68-3d0fc537d844">
You should click the "Details" for it.

**Comment by 4cecoder** [comment]
> <img width="484" alt="Screenshot 2023-12-16 at 01 10 44" src="https://github.com/objective-see/LuLu/assets/18229512/2e06c987-7baa-436c-aa68-3d0fc537d844"><br><br>
> In Security, You should click the "Details" for it, not Extensions

Let's get that in like an FAQ lol

**Comment by exrector** [comment]
> <img alt="Скриншот 2023-12-16 в 01 10 44" width="484" src="https://private-user-images.githubusercontent.com/18229512/290875620-2e06c987-7baa-436c-aa68-3d0fc537d844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjQyNzUsIm5iZiI6MTcyMDcyMzk3NSwicGF0aCI6Ii8xODIyOTUxMi8yOTA4NzU2MjAtMmUwNmM5ODctN2JhYS00MzZjLWFhNjgtM2QwZmM1MzdkODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE4NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNmE1ZmQ0NmFhYjA5YjBiYTRkN2FkYmJlMGI5NWEyNGE4OGVlYjc0ZDA4NTYyY2Q5NDE5YWZjMTk3ZDUwYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUv2Gdu0pf0P0fuv5w8U2C1E5ws2rJ0Durij1aRrWEQ"> В разделе «Безопасность» вам следует нажать «Подробности», а не «Расширения».

Could you please explain this in more detail? I don't see it in my settings
