### ISSUE TITLE
Kept approval not working properly 

### ISSUE THREAD

**Issue by F3000** [objective-see/LuLu#58]
Hi, 

 I have installed the latest beta today. 
Installed —> restart -> Lulu says  open preferences  -> click on appeov but doesn’t get a new window 

What can I do ?

**Comment by objective-see** [comment]
Once you click 'approve' in the System Preferences window the kernel extension (`LuLu.kext`) should be loaded by the OS. The installer waits on this - that is to say, until the kext is loaded. 

1) If you clicked approve, can you confirm the kext was indeed loaded, by running: `kextstat | grep lulu` from a terminal. You should see something like this:
`166    1 0xffffff7f85ce3000 0x6000     0x6000     com.objective-see.lulu (1) F97E34A4-75BA-35B6-A4DE-3DB22A6CAF44 <7 5 4 3 1>`

2) Either way, can you please also run: `log show | grep -i lulu` from a Terminal and email that output to `bugs@objective-see.com`?  This will have the information I need to troubleshoot this issue.

mahalo!

**Comment by F3000** [comment]
I have tried both versions but i see no content in the Terminal output. 

How can i completly remove Lulu and try agaain ? 

For information: 
I use OSX 10.13.4 Build 17E199

**Comment by F3000** [comment]
I have uninstalled it completly and restartet. After it i installed it again and it was fine.
