### ISSUE TITLE
LuLu 2.6.0 requires individual rule for each subscription in Vienna RSS reader

### ISSUE THREAD

**Issue by samcarter** [objective-see/LuLu#580]
I'm using Vienna (https://github.com/ViennaRSS/vienna-rss) as RSS reader. For this I have the following rule in LuLu:

![Screenshot 2024-02-01 at 11 38 43](https://github.com/objective-see/LuLu/assets/43832342/a1d07b68-cbbd-4f4f-bd44-33eadf3c88e0)

This worked great with LuLu 2.5.1 (and earlier versions). It asked me once if I allow Vienna and since then I could refresh as many subscriptions as I wanted in Vienna without any further interaction from LuLu.

---

Today I updated to LuLu 2.6.0 and LuLu started to ask me for every single subscription if I'm allowing it. Sometimes even multiple times for the same subscription. After clicking "allow" for all of them, I can refresh my subscriptions without further problems, but getting to this point is painful:

- I'm subscribed to several hundred RSS feeds, clicking "allow" several times for each one quickly adds up and is something I'd like to avoid
- All the rules are listed under the `Vienna` entry in the LuLu rules list. With several hundred entries, the list gets hard to navigate. 

Is there some way to simplify this process?

**Comment by Belluxx** [comment]
Same issue here, with some apps the `any address:any port` rule seems to not be respected and i still see the lulu request alert every time i open the software.

**Comment by objective-see** [comment]
Ah, sorry about this! 
Will dig into this today...

If you have the time/can help troubleshoot this, can you run the following via the terminal:

```
log stream --level debug --predicate="subsystem='com.objective-see.lulu'"
```

...and post any relevant output (or email to bugs@objective-see.com). 

Mahalo!

**Comment by pan93412** [comment]
I also encountered this issue in `rustup`. Log and screencast here:

## Screencast

https://github.com/objective-see/LuLu/assets/28441561/f3601d28-ffa9-41ac-b6ac-b90442f994d6

## Logs

```
2024-02-02 02:26:36.367838+0800 0x29996a   Error       0x0                  96876  0    com.objective-see.lulu.extension: [com.objective-see.lulu:extension] ERROR: code signing mismatch (signing ID): {
    signatureIdentifier = "rustup_init-2477196ebd2650c6";
    signatureSigner = 4;
    signatureStatus = 0;
} / {
    signatureIdentifier = "rustup_init";
    signatureSigner = 4;
    signatureStatus = 0;
}
2024-02-02 02:26:36.367900+0800 0x29996a   Error       0x0                  96876  0    com.objective-see.lulu.extension: [com.objective-see.lulu:extension] ERROR: code signing mismatch: {
    signatureIdentifier = "rustup_init-2477196ebd2650c6";
    signatureSigner = 4;
    signatureStatus = 0;
} / {
    signatureIdentifier = "rustup_init";
    signatureSigner = 4;
    signatureStatus = 0;
}
```

Full log: <https://app.warp.dev/block/sVGjoANi3MsOckQFwxvNjo>

**Comment by HarryMGreen** [comment]
The program I compiled by myself also has this issue, and I suspect it's because the program is not signed.

**Comment by term-i-nator** [comment]
The same happens for "curl" and "git-remote-http" when running "brew update" (for updating Homebrew). In LuLu settings I checked the mark "Allow Installed Programs" otherwise tons of windows are opened to allow access. Now access is granted automatically (which I usually don't want). In 2.5.1 I only had to allow every program only once which is absolutely ok. Now the list of rules gets longer and longer every time hombrew is trying to be updated.
![LuLu-curl-problem](https://github.com/objective-see/LuLu/assets/108834760/563d2ee5-e3db-4394-9eab-f0a472ba043a)

**Comment by objective-see** [comment]
Thanks for the bug reports & feedback 🙏🏽

There were two issues:
1. If a program's code signing info changed (e.g. `rustup_init` -> `rustup_init-2477196ebd2650c6`)
2. If a program was ad-hoc signed (e.g. `/opt/homebrew/Cellar/curl/8.6.0/bin/curl`) 

I've just checked in code that should handle/fix/address both cases. Will test more shortly, and get a new version out ASAP.

**Comment by samcarter** [comment]
@objective-see  Thanks for addressing this problem so quickly (and more generally thanks for providing such a useful application!)

Looking forward to the new version!

**Comment by cobaltdr** [comment]
Hello.

Thank you for the new version and features. Unfortunately, would like to report similar issue as above.

This is with a nativefier app (web.whatsapp.com), it keeps asking for allowing separate connections, enter any address:any port, but still not allow the connection, and it keeps cycling indefinitely. The app is unsigned I think.

<img width="1518" alt="image" src="https://github.com/objective-see/LuLu/assets/4696475/8a91c3ac-3af4-4a6e-8aff-4c4ed079f235">

Works correctly on previous version of Lulu.

**Comment by objective-see** [comment]
At your connivence, can you give this a whirl to make sure it fixes this issue?  
LuLu v2.6.1: https://github.com/objective-see/LuLu/releases/tag/v2.6.1

I've was able to replicate the issue, and now (for) me, the new code appear to fix the issue(s) ...only a single alert is shown/only one rule is needed:

![Screenshot 2024-02-02 at 10 03 20](https://github.com/objective-see/LuLu/assets/11327812/3a8d104c-7495-4503-9c5f-82cd2f9997d0)
![Screenshot 2024-02-02 at 10 03 40](https://github.com/objective-see/LuLu/assets/11327812/f28e5a84-c5a5-4a57-bde8-aa740caee5b2)


Mahalo 🙏🏽

**Comment by samcarter** [comment]
@objective-see Version 2.6.1 works great! You're awesome!

**Comment by kevinm6** [comment]
@objective-see Thank you for the fast response  and fix, and of course for the awesome piece of software!

I've create a PR to **homebrew-cask** with the new release
