### ISSUE TITLE
2.6.1. Multiple Prompts for All Apple Apps

### ISSUE THREAD

**Issue by simonf00** [objective-see/LuLu#584]
After installing 2.6.1 I get prompted multiple times each time I start an Apple App (e.g. Pages, Numbers, etc.).

<img width="1535" alt="image" src="https://github.com/objective-see/LuLu/assets/389931/6c3deff1-0f83-4159-9ccd-69706be1c802">

Even after allowing, next time I start the app I get prompted again. Reverting to 2.5.1 resolves the issue.

**Comment by objective-see** [comment]
Looking into this.
Can you post any relevant output from the log:

1. Via Terminal, run: `log stream --level debug --predicate="subsystem='com.objective-see.lulu'"`
2. Wait till spurious alert is shown & grab/post relevant output


Thanks!

**Comment by simonf00** [comment]
I've attached a log file demonstrating this with Numbers.
[NumbersLulu.log](https://github.com/objective-see/LuLu/files/14145777/NumbersLulu.log)

**Comment by objective-see** [comment]
Thanks, the log output was super helpful. 
Just released v2.6.2 that should solve this: https://github.com/objective-see/LuLu/releases/tag/v2.6.2

**Comment by simonf00** [comment]
Works!!! Thanks for the quick response and the great tools!
