### ISSUE TITLE
cannot import rules json

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [objective-see/LuLu#588]
problem is that if i use regex eg. subdomain\.domain\.com\/whatever.* in a rule, the escaped dot (\.) is not allowed in JSON. it should be double escaped \\.

i had to replace in the exported json all occurences of \. with \\. to be able to import

**Comment by objective-see** [comment]
Thanks for the bug report - should be fixed in [v2.6.3](https://github.com/objective-see/LuLu/releases/tag/v2.6.3)!
