### ISSUE TITLE
Issue with editing rules

### ISSUE THREAD

**Issue by zaqes** [objective-see/LuLu#600]
I've noted an issue with two .appex rules, StocksWidget and InternetAccountsSettingsExtensions.

If I don't have any rules for them and approve them based on Remote Endpoint it's all fine.
But if I edit one of these rules, for example changing the URL into just FQDN, then the the rules break
They then end up as "Programs within "StocksWidget.appex/" and do not work anymore.

**Comment by zaqes** [comment]
Another similar issue

Microsoft SharePoint (under OneDrive), when allowing a URL it's under this one
![Screenshot 2024-04-10 at 08 09 48](https://github.com/objective-see/LuLu/assets/75309967/cf9c8142-f2a5-4649-97a9-461b1e9417db)

but when editing it to a FQDN it goes under this
![Screenshot 2024-04-10 at 08 09 52](https://github.com/objective-see/LuLu/assets/75309967/1d05de13-393f-4724-a6ca-12647f7cb4e6)


Which means I have to allow everything from these apps instead.

**Comment by objective-see** [comment]
Thanks for reporting this issue! 
Looking into this and will provide a fix :)

**Comment by zaqes** [comment]
This now works, thanks!
