### ISSUE TITLE
local SMB connection

### ISSUE THREAD

**Issue by ektoplasmo** [objective-see/LuLu#61]
When LuLu enabled i fails to connect on a local SMB connection  , disabling while connecting  helps  !

Bug or feature ?

**Comment by heywoodlh** [comment]
I have the same issue.

**Comment by arkitype** [comment]
me too

**Comment by arkitype** [comment]
Think this could be a dupe of #21

**Comment by objective-see** [comment]
That was a bug - sorry!

This should be fixed in latest release: v0.9.5
