### ISSUE TITLE
[improvement] cmd+v shortcut with "add rule" process path window

### ISSUE THREAD

**Issue by GraOrigin** [objective-see/LuLu#62]
since version 0.9.4 does some advanced rule settings, I was not able to import my old lulu-rules.plist

the window which handles new rules does not allow a "cmd+v" shortcut, so each time I was copying a process path from the lulu-rules.plist, I had to right-click to "paste" the rule..

Would be greatly improved workflow if the shortcut would be allowed.

All the best

**Comment by objective-see** [comment]
Mahalo for reporting! 

Version 0.9.6 adds this improvement :)
