### ISSUE TITLE
Alert "Old version of LuLu installed" after building successfully

### ISSUE THREAD

**Issue by iLemonRain** [objective-see/LuLu#628]
OS: macOS 14.5 arm
I used to install Lulu v2.6.3 for trial and then uninstalled it by the steps of https://objective-see.org/products/lulu.html.
After that I  build this project by the steps of https://github.com/objective-see/LuLu/issues/568 in Xcode.
Building successfully. Then I got this alert
![img_v3_02d9_4f5fe817-500a-46ab-b24e-108025c4ccag](https://github.com/user-attachments/assets/a9833ae0-384d-4717-b325-73d3b28b7935)
No Lulu in /Applications and no process in background. I'm not sure if it related to the former installation, maybe it's just a bug. I'm stuck here.
Any discussion or help is welcomed.

**Comment by objective-see** [comment]
Was a bug in the latest code (which I've just fixed)

Note: I'd recommend building from the code in the latest release, as code committed after that is often a work in progress!
