### ISSUE TITLE
Deleted rules still allowing traffic

### ISSUE THREAD

**Issue by got3nks** [objective-see/LuLu#638]
I'm running LuLu 2.9.1 on MacOS Sequoia 15.0 (24A335).

I found out that after I delete an "Allow" rule for a specific application, when the application try to access the internet again instead of showing a pop-up to allow/block traffic, it's just allowed.

I can see the traffic of the app in the NetIQuette tool while the application is nowhere listed in the LuLu Rules.

<img width="592" alt="immagine" src="https://github.com/user-attachments/assets/e9611895-bbe4-4c80-8ac0-488a1d1fe5ad">

<img width="592" alt="immagine" src="https://github.com/user-attachments/assets/995ab2e1-0d04-434c-a379-bd283aa71063">

<img width="584" alt="immagine" src="https://github.com/user-attachments/assets/de1e1c06-19b9-424a-bbfa-2197a3a6a550">

Version 2.6.3 had the same behaviour. I updated to 2.9.1 after I noticed the issue.

**Comment by objective-see** [comment]
Thanks for the bug report, digging into this. 

Question(s):
1. Is this for new connections? 
(As once a connection is allowed, LuLu won't go back an terminate it if the "Allow" rule is removed).

2. Can you run (from a terminal): `log stream --level debug --predicate="subsystem='com.objective-see.lulu'"` and post any relevant log messages? 

Mahalo!

**Comment by objective-see** [comment]
Yes, this seems related to some of the macOS networking issues that have plagued Sequoia (specifically, whereas network flows have been misattributed to other processes the OS).
