### ISSUE TITLE
clicking on Rules cause crash each time

### ISSUE THREAD

**Issue by gondo** [objective-see/LuLu#64]
every time i click on LuLu icon in the top bar and then on Rules in context menu, the rules window flash and then disappear immediately.
when i click on Rules again, the rules window opens normally and i am presented with a diagnostic popup.
after this i can open rules without a crash
however after some (unmessurred) time, without OS restart, the same thing happens again.

**Comment by objective-see** [comment]
Sorry about this & thanks for reporting! 
The latest version of LuLu (v.0.9.5) contains some fixes, including one that should prevents a this crash.  

If the new version is still crashing, please let me know!
