### ISSUE TITLE
after Sequoia 15.0.1 update - LuLU not showing in Privacy to re-enable 

### ISSUE THREAD

**Issue by syvnul** [objective-see/LuLu#647]
Just installed the latest Apple patch 15.0.1 and after the restart the usual prompt for the extension not being enabled after clicking "open". LuLu app is not showing in the **Privacy & Security** pane where I'd normally allow. 
Running latest LuLu though Homebrew, restarted macOS, removed and re-installed LuLu both Brew and manually but no option to enable... anyone else?

thanks!

**Comment by neilraya** [comment]
It looks like macOS 15 now explicitly lists System Extensions under the “General > Login Items & Extensions” pane. You should be able to find and enable the LuLu system extension in the “Network Extensions” section of that menu.

**Comment by syvnul** [comment]
@neilraya thanks so much. I did the obvious search in Settings app but... Apple 😀  Had to go to the section you said then click on the not obvious I symbol next to the Network Extensions and then enable LuLu there.  Happy Now!
