### ISSUE TITLE
Sequoia problem

### ISSUE THREAD

**Issue by grezom** [objective-see/LuLu#649]
Under macOS Sequoia problem that LuLu does not capture open applications. In network monitor you can see them, but Lulu opens them with the fact that they can connect where they want. Tested on both 2.6.3 and 2.9.1

**Comment by objective-see** [comment]
Can you explain this a bit more? 

LuLu can only 'filter' (and thus allow/block) **new** connections ...but should be able to do so even for applications that already open. 

Meaning, if an open application attempts any new connection, this will trigger LuLu's default logic (of checking to see if an existing rules matches, or alerting, etc etc). But again, existing connections that yes will show up in a network monitor, cannot be filtered by LuLu

**Comment by grezom** [comment]
I just read in #648 that if I turn off the Apple firewall it will start working. And yes. I turned off the firewall and LuLu is working!
