### ISSUE TITLE
search in rules is case sensitive

### ISSUE THREAD

**Issue by gondo** [objective-see/LuLu#65]
when i search for process named "Process"  i type into the search bar "process" and nothing shows up.
i have to type "Process" with uppercase first letter.
this is counterintuitive and useless

**Comment by objective-see** [comment]
agreed! Code now uses `localizedCaseInsensitiveContainsString`

see: https://github.com/objective-see/LuLu/blob/92a66a488803633aa1364714a2fce81a45ca839b/mainApp/mainApp/RulesWindowController.m#L742

Next release will have this 'fix' in :)
