### ISSUE TITLE
Lulu systemextension added to dock and "not responding" (2.9.5)

### ISSUE THREAD

**Issue by jamesblonde007** [objective-see/LuLu#650]
Since installing Lulu 2.9.5 (on Intel Mac, MacOS 13.7/Ventura), I have a new icon in the dock. If I right click on this process/app, it is indicated as "not responding" and trying a force quit does nothing to remove it (neither does a restart). 

![Screenshot 2024-10-15 at 13 11 19](https://github.com/user-attachments/assets/e07b10c0-9e1e-4418-9581-8217dd405710)

![Screenshot 2024-10-15 at 13 11 28](https://github.com/user-attachments/assets/d8b25752-3375-4cd3-a6b5-96c9f6d064d4)

**Comment by chrisswanda** [comment]
Same here.  MacOS 15.0.1 (24A348)

**Comment by ChrisYangTW** [comment]
In addition to this problem, the rules in Rules>Show are cleared. (Does anyone have the same problem?)
macos 15.0.1 (24A348)

**Comment by jamesblonde007** [comment]
> In addition to this problem, the rules in Rules>Show are cleared. (Does anyone have the same problem?) macos 15.0.1 (24A348)

No, my Rules are still intact

**Comment by F1248** [comment]
Same here, but the rules are still there:
- MacBook Air M1 (MacBookAir10,1)
- macOS Sequoia 15.0.1 (24A348)
- LuLu 2.9.5

**Comment by ChrisYangTW** [comment]
> > In addition to this problem, the rules in Rules>Show are cleared. (Does anyone have the same problem?) macos 15.0.1 (24A348)
> 
> No, my Rules are still intact

Thank you. The strange thing is, after I reinstalled, the rules list came back.

**Comment by objective-see** [comment]
Thanks for the bug report(s). 
....can repo, and digging into this, to (hopefully) have a fix soon! 🤞🏽

**Comment by objective-see** [comment]
Ok should be fixed, in v2.9.6: https://github.com/objective-see/LuLu/releases/tag/v2.9.6

TIL you shouldn't invoke "Application Services" APIs from a System Extension 🫣

**Comment by jamesblonde007** [comment]
Just installed and the issue has gone. Thanks for the amazingly fast fix!

**Comment by chrisswanda** [comment]
Confirmed.  Thanks for the quick turnaround.
