### ISSUE TITLE
version 2.9.6 described as pre-release but tagged as stable release?

### ISSUE THREAD

**Issue by suschizu** [objective-see/LuLu#651]
Hi! Just a quick clarification: Is 2.9.6 a beta or the official latest version of Lulu? thanks!

**Comment by objective-see** [comment]
It's a stable pre-release 😅
Meaning I've been testing it, and running it locally with no issues!
...but as there is a ton of new code and features, I wanted to get out a version for others to try and report any bugs I've missed, before pushing out the official v3.0 and triggering the "there is a new version" mechanism to everybody.

**Comment by suschizu** [comment]
perfect - thanks for the clarification! cheers and all the best for the 3.0 release 🎉
