### ISSUE TITLE
rules export and import bug in json

### ISSUE THREAD

**Issue by silic0ns0ul** [objective-see/LuLu#662]
Running Lulu v2.9.6 on MacOS Sequoia v15.1.1. I think I found this bug when trying to import rules that I had exported. 

To recreate issue, try the following:

- Use the dropdown menu "Rules -> Export" to save rules in json file.
- Delete all rules.
- Next, try using "Rules -> Import" and select the json file. 

Probably it will say something like "error importing rules. see log for details."

Checking the json file, it seems like the name-value pair for the rule's creation timestamp is not formatted correctly because it is missing the quote marks around the timestamp value. ie, it will look like `"creation" : timestamp` when it should be `"creation" : "timestamp"`

**Comment by objective-see** [comment]
Thanks for the bug report and suggested fix (which was spot on). 🙏🏽

I've just committed a fix, the will be in the next (soon to be released) version.

**Comment by objective-see** [comment]
Fixed in [v2.9.7](https://github.com/objective-see/LuLu/releases/tag/v2.9.7)
