### ISSUE TITLE
Same destination over and over again

### ISSUE THREAD

**Issue by zaqes** [objective-see/LuLu#665]
Even though I've added the destination, Lulu still wants to add it again and again, see image
![Screenshot 2024-12-10 at 08 15 51](https://github.com/user-attachments/assets/5be55037-c1a8-4411-9afd-91bd9baa67c7)

**Comment by objective-see** [comment]
Thanks for the bug report, looking into this. 

It would be super helpful if you could also run:
```log stream --level debug --predicate="subsystem='com.objective-see.lulu'"```

And post relevant output, that should start with a log message: ` -[Rules endpointAddrMatch:rule:]` 
....then you'll see LuLu performing the endpoint matching ...which clearly appears to be broken, so I'm hoping these log message shed some insight into why.

**Comment by objective-see** [comment]
Fixed in [v2.9.7](https://github.com/objective-see/LuLu/releases/tag/v2.9.7)

**Comment by zaqes** [comment]
Do you still need the debug?
