### ISSUE TITLE
How to add permanent rule from alert pop-up

### ISSUE THREAD

**Issue by samcarter** [objective-see/LuLu#667]
If a new program is trying to make a connection, I get the following alert pop-up:

![Screenshot 2024-12-12 at 11 52 08](https://github.com/user-attachments/assets/416c00c5-e669-432f-9cf4-83cc13b6418a)

Once I select "Block" or "Allow" things work as expected until I restart the computer or quit/reopen LuLu. Then I get the same pop-up again.

- I double checked that for "Rule Duration" the "Always" option is selected
- after I selected "Block" or "Allow" I can see a corresponding rule in the LuLu rule overview. After the restart, I can no longer see the rule there.
- If I manually create a rule in the LuLu rules overview window, they will still work after a restart
- this behaviour seems to have started with the new UI for alerts, I didn't notice it before

I'm using:

- LuLu Version 2.9.6
- macOS 14.7.2

**Comment by objective-see** [comment]
Thanks for the bug report! 
Just pushed a fix and will release a new version shortly 🙏🏽

**Comment by samcarter** [comment]
@objective-see Thank you very, very much!

**Comment by objective-see** [comment]
Fixed in [v2.9.7](https://github.com/objective-see/LuLu/releases/tag/v2.9.7)

**Comment by samcarter** [comment]
Just tested and it works great with v2.9.7 Thanks again!
