### ISSUE TITLE
Can't uninstall Lulu

### ISSUE THREAD

**Issue by Omek6** [objective-see/LuLu#669]
Hi I finally upgraded to an M4 Mini with the latest version of Sequoia. My last dead Mac was still running lulu 1.2.3. I don't see any option from the Lulu menu to uninstall or quit it. I had to quit out of it from Activity Monitor. I tried putting it in the trash and copying the newest version and I just get this. I don't know how to proceed. How do I uninstall it if there isn't an option?

![353408595-a9833ae0-384d-4717-b325-73d3b28b7935](https://github.com/user-attachments/assets/d310c034-2346-4f17-9e46-140ea3691156)

![Screenshot 2024-12-12 at 2 21 49 PM](https://github.com/user-attachments/assets/7e05cbdd-3ef6-44d2-80aa-9392fc34d6ce)

**Comment by objective-see** [comment]
![image](https://github.com/user-attachments/assets/71eccfd3-771f-4b82-8867-c114cb50a188)

LuLu v1.2.3:
https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.2.3.zip

**Comment by Omek6** [comment]
![Screenshot 2024-12-12 at 3 28 11 PM](https://github.com/user-attachments/assets/1b16e028-d56e-485c-99b1-53c4a5b770de)

**Comment by objective-see** [comment]
The (old) uninstaller might (partially) fail if certain components have been manually removed. 
It'd first re-try installing the new version again ...as maybe you'll be good to go now. 

If not, you can follow these steps to manually / fully remove the old version:

```
launchctl unload /Library/LaunchDaemons/com.objective-see.lulu.plist
rm /Library/LaunchDaemons/com.objective-see.lulu.plist

rm -rf /Applications/LuLu.app
rm -rf /Library/Objective-See/LuLu/

kextunload -b com.objective-see.lulu
rm -rf /Library/Extensions/LuLu.kext
```

(Note: Run these commands as root. Some might fail if those components have been uninstalled manually, or removed by running the uninstaller).

**Comment by Omek6** [comment]
Thank you so much! That resolved it. The ktext didn't exist which was weird. That may have been the hangup. I was jumping about 8 Mac OS versions, so I'm guessing it got removed in the process since Apple has added all these new security functions. I have to retrain Lulu, but I expected my rules might not make it. Thanks again!

**Comment by objective-see** [comment]
You welcome, glad that helped :)
