### ISSUE TITLE
[Request] Lockdown Mode

### ISSUE THREAD

**Issue by Firerouge** [objective-see/LuLu#70]
Would be nice to have an option that's somewhat opposite the passive mode, in which it silently runs without alerts, ignoring existing rules, and new connections will be automatically blocked (but ideally no rule created during this).

**Comment by objective-see** [comment]
Mahalo! 

Added to version 0.9.6:
<img width="593" alt="screen shot 2018-07-04 at 2 16 23 pm" src="https://user-images.githubusercontent.com/11327812/42274342-0178ae56-7f95-11e8-8b8e-47c8e04917e3.png">
