### ISSUE TITLE
(closed) LuLu 0.9.6 can not handle Network Lock

### ISSUE THREAD

**Issue by GraOrigin** [objective-see/LuLu#72]
Hi,

newest version can not handle the Network Lock of Eddie 2.16.1 [https://github.com/AirVPN/Eddie](url)
Unable to even get Server Ping when enabled globally. LuLu does not ask for permission of any new process trying to access Network, nor does it allow rules which already were set to 'allow'..
Happening on MacOS 10.12.6

Kind regards

**Comment by objective-see** [comment]
Do you have a download link to a pre-built macOS `2.16.1` installer? 
(https://github.com/AirVPN/Eddie/releases and https://airvpn.org/macosx/ just lists `2.15.2` as the latest)

Tested with version Eddie `2.15.2` and it appears to work (i.e. even with Network Lock enabled, Eddie's network traffic for account login triggers a LuLu alert, then, when allowed, contacts server). 

Maybe something changed in `2.16.1`?

**Comment by GraOrigin** [comment]
must have, here's a direct link to 2.16.1
[https://airvpn.org/mirrors/eddie.website/download/?platform=macos&arch=x64&ui=ui&format=disk.dmg&version=experimental&r=0.3888236541014667](url)

grabbed from
[https://airvpn.org/macosx/](url)
after selecting all the above, used "other version" below download-button, to change to "experimental"

**Comment by objective-see** [comment]
Hrmm seems to work fine for me:

1) Install LuLu (`0.9.6`)
2) Install Eddie `2.16.1`
3) Activate Eddie's Network Lock
4) Select a server and click 'Login'

LuLu detects Eddie's use of `curl` for comms
<img width="854" alt="screen shot 2018-07-19 at 11 52 42 pm" src="https://user-images.githubusercontent.com/11327812/42969444-dcbef7b6-8bae-11e8-9b30-c994d7c925ef.png">

If you click 'Allow' login check continues...
a) Can you make sure `curl` wasn't previously blocked?
b) Do you see anything in the log? 
(try: `log stream | grep -i LuLu` from the terminal, and repeat)

**Comment by GraOrigin** [comment]
Strangest things happened..
curl was not blocked previously (all worked fine before 2.16.1) 
but somehow LuLu blocked 2/3 web-browsers I use, with also no change of rule (worked fine)
I started the log stream and since then LuLu (0.9.6) seems to have come to life again with displaying 'block or allow' windows.
Anyway, installed 0.9.7 and this problem seems to be solved! 
Thank you for your quick action - Kind regards
