### ISSUE TITLE
Uninstall not working Lulu Helper

### ISSUE THREAD

**Issue by doreybenjamin** [objective-see/LuLu#92]
I try to uninstall LuLu but i can't, Lulu Helper appear after each restart.
He is here : 
/private/var/folders/jt/k60jr52s2bgfmd07hqywb9bm0000gp/T/AppTranslocation/60E56C49-4597-433A-AC99-10D7528C364A/d/LuLu.app/Contents/Library/LoginItems/LuLu Helper.app/Contents/MacOS/LuLu Helper

I'm on macOS Mojave

Regards,

**Comment by doreybenjamin** [comment]
I fix this issues, i have just close session.

**Comment by objective-see** [comment]
Ok, glad that fixed it!
